import { crmCompanies } from "@/app/(main)/dashboard/crm/_components/crm-data/companies";
import { salesOwners } from "@/app/(main)/dashboard/crm/_components/crm-data/sales-team";

import type { Lead, LeadSource, LeadStatus } from "./schema";

const today = new Date(2026, 7, 16);

function daysAgo(n: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}

function daysAhead(n: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}

export const leads: Lead[] = [
  {
    id: "lead-001",
    name: "Cameron Ruiz",
    jobTitle: "VP of Research",
    company: crmCompanies[0].name,
    email: "cameron.ruiz@asteronbio.example.com",
    phone: "+1 (555) 201-0001",
    source: "Website",
    status: "Qualified",
    score: 88,
    ownerId: salesOwners[0].id,
    lastActivity: daysAgo(2),
    nextActivity: daysAhead(1),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(2),
    location: "San Francisco, CA",
    timezone: "America/Los_Angeles",
    preferredContact: "email",
    tags: ["enterprise", "q1-budget", "decision-maker"],
    companyWebsite: "https://asteronbio.example.com",
    companyIndustry: "Biotechnology",
    companySize: "500-1000",
    activityTimeline: [
      {
        id: "a1",
        type: "creation",
        title: "Lead created",
        description: "Lead was created from website form submission",
        timestamp: daysAgo(180),
        actor: "System",
      },
      {
        id: "a2",
        type: "email",
        title: "Welcome email sent",
        description: "Sent initial outreach email introducing our platform capabilities",
        timestamp: daysAgo(175),
        actor: "Arham Khan",
        outcome: "Opened",
      },
      {
        id: "a3",
        type: "call",
        title: "Discovery call",
        description: "30-minute discovery call to understand Asteron's research infrastructure needs",
        timestamp: daysAgo(160),
        actor: "Arham Khan",
        outcome: "Completed",
      },
      {
        id: "a4",
        type: "email",
        title: "Follow-up email",
        description: "Shared case study and pricing overview after discovery call",
        timestamp: daysAgo(158),
        actor: "Arham Khan",
        outcome: "Replied",
      },
      {
        id: "a5",
        type: "meeting",
        title: "Product demo",
        description: "Live product demo with Cameron and 3 members of the research team",
        timestamp: daysAgo(140),
        actor: "Arham Khan",
        outcome: "Completed",
      },
      {
        id: "a6",
        type: "status_change",
        title: "Status changed to Contacted",
        description: "Lead moved from New to Contacted after initial engagement",
        timestamp: daysAgo(139),
        actor: "Arham Khan",
      },
      {
        id: "a7",
        type: "task",
        title: "Send proposal",
        description: "Prepared and sent detailed proposal with custom pricing",
        timestamp: daysAgo(120),
        actor: "Arham Khan",
        outcome: "Completed",
      },
      {
        id: "a8",
        type: "call",
        title: "Proposal review call",
        description: "Reviewed proposal with Cameron and addressed questions about data migration",
        timestamp: daysAgo(100),
        actor: "Arham Khan",
        outcome: "Completed",
      },
      {
        id: "a9",
        type: "email",
        title: "Pricing negotiation",
        description: "Cameron requested a 15% discount for annual commitment",
        timestamp: daysAgo(80),
        actor: "Arham Khan",
        outcome: "Replied",
      },
      {
        id: "a10",
        type: "status_change",
        title: "Status changed to Qualified",
        description: "Lead qualified after budget and timeline confirmation",
        timestamp: daysAgo(60),
        actor: "Arham Khan",
      },
      {
        id: "a11",
        type: "meeting",
        title: "Executive alignment meeting",
        description: "Met with Asteron's CFO to finalize budget allocation for the platform",
        timestamp: daysAgo(30),
        actor: "Arham Khan",
        outcome: "Completed",
      },
      {
        id: "a12",
        type: "note",
        title: "Internal note",
        description: "Cameron confirmed Q1 2027 budget cycle for the purchase decision",
        timestamp: daysAgo(14),
        actor: "Arham Khan",
      },
      {
        id: "a13",
        type: "email",
        title: "Contract draft shared",
        description: "Sent preliminary contract draft for internal review",
        timestamp: daysAgo(5),
        actor: "Arham Khan",
        outcome: "Opened",
      },
      {
        id: "a14",
        type: "call",
        title: "Follow-up call scheduled",
        description: "Scheduled call for tomorrow to discuss final contract terms",
        timestamp: daysAgo(2),
        actor: "Arham Khan",
        outcome: "Scheduled",
      },
    ],
    tasks: [
      {
        id: "t1",
        title: "Follow-up on contract review",
        dueDate: daysAgo(1),
        status: "completed",
        priority: "high",
        ownerId: salesOwners[0].id,
      },
      {
        id: "t2",
        title: "Send updated proposal with revised pricing",
        dueDate: daysAhead(0),
        status: "in_progress",
        priority: "high",
        ownerId: salesOwners[0].id,
      },
      {
        id: "t3",
        title: "Schedule product demo for technical team",
        dueDate: daysAhead(5),
        status: "pending",
        priority: "medium",
        ownerId: salesOwners[0].id,
      },
      {
        id: "t4",
        title: "Prepare ROI analysis document",
        dueDate: daysAhead(10),
        status: "pending",
        priority: "medium",
        ownerId: salesOwners[0].id,
      },
      {
        id: "t5",
        title: "Introductory call completed",
        dueDate: daysAgo(20),
        status: "completed",
        priority: "low",
        ownerId: salesOwners[0].id,
      },
    ],
    notes: [
      {
        id: "n1",
        content:
          "Referred by Nina Petrova at BlueHaven. Cameron is evaluating alternatives to their current research platform. Budget approved for Q1 2027.",
        author: "Arham Khan",
        createdAt: daysAgo(170),
        pinned: true,
      },
      {
        id: "n2",
        content:
          "Cameron mentioned they need advanced analytics and team collaboration features. Their current platform lacks real-time data sharing.",
        author: "Arham Khan",
        createdAt: daysAgo(140),
      },
      {
        id: "n3",
        content:
          "Product demo went very well. Cameron was particularly impressed with the analytics dashboard. Wants to see a comparison with their current tool.",
        author: "Arham Khan",
        createdAt: daysAgo(139),
      },
      {
        id: "n4",
        content: "Budget flexible for the right solution. Q1 2027 purchase cycle confirmed. CFO is supportive.",
        author: "Arham Khan",
        createdAt: daysAgo(60),
        pinned: true,
      },
      {
        id: "n5",
        content: "Cameron wants to move fast. Looking for proposal by end of month.",
        author: "Arham Khan",
        createdAt: daysAgo(5),
      },
    ],
  },
  {
    id: "lead-002",
    name: "Nina Petrova",
    jobTitle: "Director of Engineering",
    company: crmCompanies[1].name,
    email: "nina.petrova@bluehaven.example.com",
    phone: "+1 (555) 201-0002",
    source: "Referral",
    status: "Contacted",
    score: 72,
    ownerId: salesOwners[1].id,
    lastActivity: daysAgo(5),
    nextActivity: daysAhead(3),
    createdAt: daysAgo(120),
  },
  {
    id: "lead-003",
    name: "Tomas Lindqvist",
    jobTitle: "CTO",
    company: crmCompanies[2].name,
    email: "tomas.lindqvist@cinderhealth.example.com",
    phone: "+1 (555) 201-0003",
    source: "LinkedIn",
    status: "New",
    score: 65,
    ownerId: salesOwners[2].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(2),
    createdAt: daysAgo(5),
  },
  {
    id: "lead-004",
    name: "Ava Thompson",
    jobTitle: "Operations Manager",
    company: crmCompanies[3].name,
    email: "ava.thompson@driftmfg.example.com",
    phone: "+1 (555) 201-0004",
    source: "Event",
    status: "Nurturing",
    score: 45,
    ownerId: salesOwners[3].id,
    lastActivity: daysAgo(14),
    nextActivity: daysAhead(7),
    createdAt: daysAgo(200),
  },
  {
    id: "lead-005",
    name: "Mateo Silva",
    jobTitle: "Supply Chain Director",
    company: crmCompanies[4].name,
    email: "mateo.silva@everline.example.com",
    phone: "+1 (555) 201-0005",
    source: "Partner",
    status: "Qualified",
    score: 82,
    ownerId: salesOwners[4].id,
    lastActivity: daysAgo(3),
    nextActivity: daysAhead(1),
    createdAt: daysAgo(150),
  },
  {
    id: "lead-006",
    name: "Priya Raman",
    jobTitle: "Managing Director",
    company: crmCompanies[5].name,
    email: "priya.raman@fieldstone.example.com",
    phone: "+1 (555) 201-0006",
    source: "Outbound",
    status: "Contacted",
    score: 78,
    ownerId: salesOwners[0].id,
    lastActivity: daysAgo(4),
    nextActivity: daysAhead(2),
    createdAt: daysAgo(90),
  },
  {
    id: "lead-007",
    name: "Felix Bauer",
    jobTitle: "Creative Director",
    company: crmCompanies[6].name,
    email: "felix.bauer@granitestudios.example.com",
    phone: "+1 (555) 201-0007",
    source: "Organic Search",
    status: "New",
    score: 55,
    ownerId: salesOwners[5].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(4),
    createdAt: daysAgo(10),
  },
  {
    id: "lead-008",
    name: "Hana Sato",
    jobTitle: "Head of Product",
    company: crmCompanies[7].name,
    email: "hana.sato@halcyon.example.com",
    phone: "+1 (555) 201-0008",
    source: "Paid Campaign",
    status: "Unqualified",
    score: 22,
    ownerId: salesOwners[6].id,
    lastActivity: daysAgo(30),
    nextActivity: null,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(30),
    location: "Seattle, WA",
    timezone: "America/Los_Angeles",
    preferredContact: "phone",
    tags: ["inbound"],
    activityTimeline: [
      {
        id: "a1",
        type: "creation",
        title: "Lead created",
        description: "Lead was created from a paid campaign landing page",
        timestamp: daysAgo(60),
        actor: "System",
      },
      {
        id: "a2",
        type: "email",
        title: "Welcome email sent",
        description: "Sent initial follow-up after campaign form submission",
        timestamp: daysAgo(58),
        actor: "Isla Grant",
        outcome: "Opened",
      },
      {
        id: "a3",
        type: "call",
        title: "Outreach call",
        description: "Attempted outreach call to discuss product interest",
        timestamp: daysAgo(45),
        actor: "Isla Grant",
        outcome: "No Answer",
      },
      {
        id: "a4",
        type: "email",
        title: "Follow-up email",
        description: "Sent follow-up email with product brochure after no answer on call",
        timestamp: daysAgo(44),
        actor: "Isla Grant",
        outcome: "Opened",
      },
      {
        id: "a5",
        type: "status_change",
        title: "Status changed to Unqualified",
        description: "Lead marked as unqualified due to budget constraints",
        timestamp: daysAgo(30),
        actor: "Isla Grant",
      },
    ],
    notes: [
      {
        id: "n1",
        content:
          "Hana's team is interested but doesn't have budget allocated this fiscal year. Revisit in Q2 next year.",
        author: "Isla Grant",
        createdAt: daysAgo(30),
      },
    ],
  },
  {
    id: "lead-086",
    name: "Graham Fraser",
    jobTitle: "Director of Procurement",
    company: "Caledonia Textiles",
    email: "graham.fraser@caledoniatextiles.example.com",
    phone: "+44 20 7946 0958",
    source: "Event",
    status: "Unqualified",
    score: 20,
    ownerId: salesOwners[0].id,
    lastActivity: daysAgo(60),
    nextActivity: null,
    createdAt: daysAgo(150),
    updatedAt: daysAgo(45),
    archivedAt: daysAgo(45),
    archivedBy: "arham",
    location: "London, UK",
    timezone: "Europe/London",
    preferredContact: "email",
    tags: ["inbound"],
    activityTimeline: [
      {
        id: "a1",
        type: "creation",
        title: "Lead created",
        description: "Lead was created after meeting at London Tech Summit",
        timestamp: daysAgo(150),
        actor: "System",
      },
      {
        id: "a2",
        type: "email",
        title: "Welcome email sent",
        description: "Sent initial follow-up after conference meeting",
        timestamp: daysAgo(145),
        actor: "Arham Khan",
        outcome: "Opened",
      },
      {
        id: "a3",
        type: "call",
        title: "Discovery call",
        description: "Had a 25-minute call to understand their procurement needs",
        timestamp: daysAgo(120),
        actor: "Arham Khan",
        outcome: "Completed",
      },
      {
        id: "a4",
        type: "status_change",
        title: "Status changed to Unqualified",
        description: "Lead marked as unqualified - budget frozen for the fiscal year",
        timestamp: daysAgo(60),
        actor: "Arham Khan",
      },
    ],
    tasks: [],
    notes: [
      {
        id: "n1",
        content:
          "Met Graham at London Tech Summit. He was interested but budget is frozen for this fiscal year. No point continuing pursuit.",
        author: "Arham Khan",
        createdAt: daysAgo(140),
      },
    ],
  },
  {
    id: "lead-087",
    name: "Ines Ferreira",
    jobTitle: "VP of Marketing",
    company: "Lisbon Digital Agency",
    email: "ines.ferreira@lisbondigital.example.com",
    phone: "+351 210 123 456",
    source: "Referral",
    status: "Contacted",
    score: 55,
    ownerId: salesOwners[1].id,
    lastActivity: daysAgo(40),
    nextActivity: null,
    createdAt: daysAgo(95),
    updatedAt: daysAgo(40),
    archivedAt: daysAgo(30),
    archivedBy: "ammar",
    location: "Lisbon, Portugal",
    timezone: "Europe/Lisbon",
    preferredContact: "linkedin",
    tags: ["referral", "marketing"],
    activityTimeline: [
      {
        id: "a1",
        type: "creation",
        title: "Lead created",
        description: "Lead was created from a referral by Priya Raman",
        timestamp: daysAgo(95),
        actor: "System",
      },
      {
        id: "a2",
        type: "email",
        title: "Follow-up email",
        description: "Sent introduction email with case studies",
        timestamp: daysAgo(90),
        actor: "Ammar Hassan",
        outcome: "Replied",
      },
      {
        id: "a3",
        type: "call",
        title: "Intro call",
        description: "Had a 30-minute intro call about platform capabilities",
        timestamp: daysAgo(70),
        actor: "Ammar Hassan",
        outcome: "Completed",
      },
      {
        id: "a4",
        type: "status_change",
        title: "Status changed to Contacted",
        description: "Lead engaged in conversation but went silent after intro call",
        timestamp: daysAgo(40),
        actor: "Ammar Hassan",
      },
    ],
    tasks: [],
    notes: [
      {
        id: "n1",
        content:
          "Ines was referred by Priya. She had a good intro call but has gone silent. Possibly busy with a campaign launch.",
        author: "Ammar Hassan",
        createdAt: daysAgo(70),
      },
    ],
  },
  {
    id: "lead-088",
    name: "Nikolai Petrov",
    jobTitle: "Chief Technology Officer",
    company: "Ural Innovations",
    email: "nikolai.petrov@uralinnovations.example.com",
    source: "LinkedIn",
    status: "New",
    score: 40,
    ownerId: null,
    lastActivity: daysAgo(20),
    nextActivity: null,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(20),
    archivedAt: daysAgo(15),
    archivedBy: "arham",
    location: "Moscow, Russia",
    timezone: "Europe/Moscow",
    preferredContact: "email",
    tags: [],
    activityTimeline: [
      {
        id: "a1",
        type: "creation",
        title: "Lead created",
        description: "Lead was created from LinkedIn connection request",
        timestamp: daysAgo(60),
        actor: "System",
      },
      {
        id: "a2",
        type: "email",
        title: "Initial outreach",
        description: "Sent LinkedIn message and email introducing our platform",
        timestamp: daysAgo(50),
        actor: "Arham Khan",
        outcome: "Opened",
      },
    ],
    tasks: [],
    notes: [
      {
        id: "n1",
        content:
          "Nikolai connected on LinkedIn but hasn't responded to outreach. May not be a good fit given location and timezone.",
        author: "Arham Khan",
        createdAt: daysAgo(50),
      },
    ],
  },
  {
    id: "lead-089",
    name: "Fatou Diallo",
    jobTitle: "Head of Operations",
    company: "West Africa Logistics",
    email: "fatou.diallo@waalogistics.example.com",
    source: "Website",
    status: "Nurturing",
    score: 35,
    ownerId: salesOwners[2].id,
    lastActivity: daysAgo(55),
    nextActivity: null,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(55),
    archivedAt: daysAgo(25),
    archivedBy: "sofia",
    location: "Dakar, Senegal",
    timezone: "Africa/Dakar",
    preferredContact: "phone",
    tags: ["inbound", "logistics"],
    activityTimeline: [
      {
        id: "a1",
        type: "creation",
        title: "Lead created",
        description: "Lead was created from website form submission",
        timestamp: daysAgo(180),
        actor: "System",
      },
      {
        id: "a2",
        type: "email",
        title: "Welcome email",
        description: "Sent initial follow-up with product overview",
        timestamp: daysAgo(175),
        actor: "Sofia Marchetti",
        outcome: "Opened",
      },
      {
        id: "a3",
        type: "call",
        title: "Follow-up call",
        description: "Discussed logistics management needs and timeline",
        timestamp: daysAgo(120),
        actor: "Sofia Marchetti",
        outcome: "Completed",
      },
      {
        id: "a4",
        type: "status_change",
        title: "Status changed to Nurturing",
        description: "Lead interested but timeline pushed to next year",
        timestamp: daysAgo(55),
        actor: "Sofia Marchetti",
      },
    ],
    tasks: [],
    notes: [
      {
        id: "n1",
        content:
          "Fatou is interested in our platform for their logistics operations but timeline is pushed to next year. Low priority nurturing.",
        author: "Sofia Marchetti",
        createdAt: daysAgo(120),
      },
    ],
  },
  {
    id: "lead-009",
    name: "Omar Farouk",
    jobTitle: "Investment Analyst",
    company: crmCompanies[8].name,
    email: "omar.farouk@ironcrest.example.com",
    phone: "+1 (555) 201-0009",
    source: "Referral",
    status: "Qualified",
    score: 91,
    ownerId: salesOwners[7].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(1),
    createdAt: daysAgo(100),
  },
  {
    id: "lead-010",
    name: "Lena Kowalski",
    jobTitle: "Infrastructure Lead",
    company: crmCompanies[9].name,
    email: "lena.kowalski@juniper.example.com",
    phone: "+1 (555) 201-0010",
    source: "LinkedIn",
    status: "New",
    score: 60,
    ownerId: salesOwners[1].id,
    lastActivity: daysAgo(2),
    nextActivity: daysAhead(5),
    createdAt: daysAgo(8),
  },
  {
    id: "lead-011",
    name: "Rosa Delgado",
    jobTitle: "E-commerce Manager",
    company: crmCompanies[10].name,
    email: "rosa.delgado@kestrel.example.com",
    source: "Website",
    status: "Nurturing",
    score: 38,
    ownerId: salesOwners[2].id,
    lastActivity: daysAgo(21),
    nextActivity: null,
    createdAt: daysAgo(240),
  },
  {
    id: "lead-012",
    name: "Jonas Weber",
    jobTitle: "Clinical Operations",
    company: crmCompanies[11].name,
    email: "jonas.weber@lattice.example.com",
    phone: "+1 (555) 201-0012",
    source: "Event",
    status: "Contacted",
    score: 70,
    ownerId: salesOwners[0].id,
    lastActivity: daysAgo(6),
    nextActivity: daysAhead(3),
    createdAt: daysAgo(75),
  },
  {
    id: "lead-013",
    name: "Claire Dubois",
    jobTitle: "VP of Sales",
    company: crmCompanies[12].name,
    email: "claire.dubois@marinerfoods.example.com",
    phone: "+1 (555) 201-0013",
    source: "Outbound",
    status: "Qualified",
    score: 85,
    ownerId: salesOwners[3].id,
    lastActivity: daysAgo(2),
    nextActivity: daysAhead(1),
    createdAt: daysAgo(130),
  },
  {
    id: "lead-014",
    name: "Samira Haddad",
    jobTitle: "Energy Program Director",
    company: crmCompanies[13].name,
    email: "samira.haddad@northfield.example.com",
    phone: "+1 (555) 201-0014",
    source: "Partner",
    status: "New",
    score: 68,
    ownerId: salesOwners[4].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(2),
    createdAt: daysAgo(3),
  },
  {
    id: "lead-015",
    name: "Derek Holloway",
    jobTitle: "Sales Director",
    email: "derek.holloway@example.com",
    phone: "+1 (555) 201-0015",
    source: "Referral",
    status: "Nurturing",
    score: 35,
    ownerId: salesOwners[5].id,
    lastActivity: daysAgo(28),
    nextActivity: null,
    createdAt: daysAgo(270),
  },
  {
    id: "lead-016",
    name: "Mei Chen",
    jobTitle: "Product Manager",
    company: "Quantum Logistics Corp",
    email: "mei.chen@quantumlogistics.example.com",
    phone: "+1 (555) 201-0016",
    source: "Organic Search",
    status: "Contacted",
    score: 58,
    ownerId: salesOwners[6].id,
    lastActivity: daysAgo(7),
    nextActivity: daysAhead(4),
    createdAt: daysAgo(45),
  },
  {
    id: "lead-017",
    name: "Raj Patel",
    jobTitle: "Founder & CEO",
    company: "Vantage Health Tech",
    email: "raj.patel@vantageht.example.com",
    phone: "+1 (555) 201-0017",
    source: "LinkedIn",
    status: "Qualified",
    score: 94,
    ownerId: salesOwners[7].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(1),
    createdAt: daysAgo(40),
  },
  {
    id: "lead-018",
    name: "Sophie Laurent",
    jobTitle: "Marketing VP",
    company: "Meridian Brands",
    email: "sophie.laurent@meridianbrands.example.com",
    phone: "+1 (555) 201-0018",
    source: "Paid Campaign",
    status: "New",
    score: 42,
    ownerId: salesOwners[0].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(6),
    createdAt: daysAgo(2),
  },
  {
    id: "lead-019",
    name: "James Okafor",
    jobTitle: "Head of Revenue",
    email: "james.okafor@example.com",
    source: "Event",
    status: "Unqualified",
    score: 18,
    ownerId: salesOwners[1].id,
    lastActivity: daysAgo(45),
    nextActivity: null,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(45),
    location: "New York, NY",
    timezone: "America/New_York",
    preferredContact: "linkedin",
    tags: ["inbound"],
    activityTimeline: [
      {
        id: "a1",
        type: "creation",
        title: "Lead created",
        description: "Lead was created after meeting at SaaStr Annual conference",
        timestamp: daysAgo(90),
        actor: "System",
      },
      {
        id: "a2",
        type: "email",
        title: "Follow-up email sent",
        description: "Sent follow-up email with conference materials and pricing overview",
        timestamp: daysAgo(85),
        actor: "Ammar Hassan",
        outcome: "Opened",
      },
      {
        id: "a3",
        type: "call",
        title: "Intro call",
        description: "Had a 20-minute introductory call to assess interest level",
        timestamp: daysAgo(70),
        actor: "Ammar Hassan",
        outcome: "Completed",
      },
      {
        id: "a4",
        type: "email",
        title: "Budget concern raised",
        description: "James mentioned current budget constraints and prioritization issues",
        timestamp: daysAgo(55),
        actor: "Ammar Hassan",
        outcome: "Replied",
      },
      {
        id: "a5",
        type: "status_change",
        title: "Status changed to Unqualified",
        description: "Lead marked as unqualified due to budget and timing constraints",
        timestamp: daysAgo(45),
        actor: "Ammar Hassan",
      },
    ],
    tasks: [],
    notes: [
      {
        id: "n1",
        content:
          "Met James at SaaStr Annual. He showed interest in our analytics features but mentioned tight budgets for the next 6 months.",
        author: "Ammar Hassan",
        createdAt: daysAgo(85),
      },
    ],
  },
  {
    id: "lead-020",
    name: "Elena Volkov",
    jobTitle: "Director of Partnerships",
    company: "Cobalt Aerospace",
    email: "elena.volkov@cobaltaero.example.com",
    phone: "+1 (555) 201-0020",
    source: "Partner",
    status: "Contacted",
    score: 74,
    ownerId: salesOwners[2].id,
    lastActivity: daysAgo(3),
    nextActivity: daysAhead(2),
    createdAt: daysAgo(55),
  },
  {
    id: "lead-021",
    name: "Benjamin Torres",
    jobTitle: "IT Director",
    company: "Horizon Utilities",
    email: "benjamin.torres@horizonutil.example.com",
    phone: "+1 (555) 201-0021",
    source: "Website",
    status: "Nurturing",
    score: 48,
    ownerId: salesOwners[3].id,
    lastActivity: daysAgo(12),
    nextActivity: daysAhead(14),
    createdAt: daysAgo(180),
  },
  {
    id: "lead-022",
    name: "Anika Johansson",
    jobTitle: "CEO",
    company: "Nordic Wave Studios",
    email: "anika.johansson@nordicwave.example.com",
    source: "Referral",
    status: "Qualified",
    score: 87,
    ownerId: salesOwners[4].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(1),
    createdAt: daysAgo(65),
  },
  {
    id: "lead-023",
    name: "Carlos Mendez",
    jobTitle: "Procurement Lead",
    company: "Apex Industrial",
    email: "carlos.mendez@apexindustrial.example.com",
    phone: "+1 (555) 201-0023",
    source: "Outbound",
    status: "New",
    score: 52,
    ownerId: salesOwners[5].id,
    lastActivity: daysAgo(2),
    nextActivity: daysAhead(5),
    createdAt: daysAgo(7),
  },
  {
    id: "lead-024",
    name: "Aisha Nkemdirim",
    jobTitle: "Growth Lead",
    company: "Luminary EdTech",
    email: "aisha.nkemdirim@luminaryed.example.com",
    phone: "+1 (555) 201-0024",
    source: "LinkedIn",
    status: "Contacted",
    score: 63,
    ownerId: salesOwners[6].id,
    lastActivity: daysAgo(8),
    nextActivity: daysAhead(3),
    createdAt: daysAgo(35),
  },
  {
    id: "lead-025",
    name: "William Feng",
    jobTitle: "Chief Technology Officer",
    company: "Pacific Rim Robotics",
    email: "william.feng@pacificrimr.example.com",
    phone: "+1 (555) 201-0025",
    source: "Event",
    status: "Qualified",
    score: 90,
    ownerId: salesOwners[7].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(1),
    createdAt: daysAgo(50),
  },
  {
    id: "lead-026",
    name: "Fatima Al-Rashid",
    jobTitle: "Director of Innovation",
    company: "Zephyr Energy Solutions",
    email: "fatima.alrashid@zephyrenergy.example.com",
    phone: "+1 (555) 201-0026",
    source: "Paid Campaign",
    status: "Nurturing",
    score: 33,
    ownerId: salesOwners[0].id,
    lastActivity: daysAgo(35),
    nextActivity: null,
    createdAt: daysAgo(300),
  },
  {
    id: "lead-027",
    name: "Oliver Strand",
    jobTitle: "Head of Business Dev",
    company: "Fjord Media Group",
    email: "oliver.strand@fjordmedia.example.com",
    source: "Organic Search",
    status: "New",
    score: 47,
    ownerId: salesOwners[1].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(4),
    createdAt: daysAgo(4),
  },
  {
    id: "lead-028",
    name: "Yuki Tanaka",
    jobTitle: "R&D Manager",
    company: "Sakura Biomedical",
    email: "yuki.tanaka@sakurabio.example.com",
    phone: "+1 (555) 201-0028",
    source: "Referral",
    status: "Contacted",
    score: 76,
    ownerId: salesOwners[2].id,
    lastActivity: daysAgo(4),
    nextActivity: daysAhead(2),
    createdAt: daysAgo(25),
  },
  {
    id: "lead-029",
    name: "Marcus Williams",
    jobTitle: "VP of Operations",
    company: "Summit Construction",
    email: "marcus.williams@summitconstr.example.com",
    phone: "+1 (555) 201-0029",
    source: "Website",
    status: "Unqualified",
    score: 15,
    ownerId: salesOwners[3].id,
    lastActivity: daysAgo(60),
    nextActivity: null,
    createdAt: daysAgo(120),
  },
  {
    id: "lead-030",
    name: "Isabella Rossi",
    jobTitle: "Creative Strategist",
    company: "Aurora Design Studio",
    email: "isabella.rossi@auroradesign.example.com",
    source: "LinkedIn",
    status: "New",
    score: 56,
    ownerId: salesOwners[4].id,
    lastActivity: daysAgo(2),
    nextActivity: daysAhead(3),
    createdAt: daysAgo(6),
  },
  {
    id: "lead-031",
    name: "Daniel Kim",
    jobTitle: "Solutions Architect",
    company: "Cirrus Cloud Services",
    email: "daniel.kim@cirruscloud.example.com",
    phone: "+1 (555) 201-0031",
    source: "Event",
    status: "Qualified",
    score: 83,
    ownerId: salesOwners[5].id,
    lastActivity: daysAgo(2),
    nextActivity: daysAhead(1),
    createdAt: daysAgo(80),
  },
  {
    id: "lead-032",
    name: "Sarah Mitchell",
    jobTitle: "COO",
    email: "sarah.mitchell@example.com",
    phone: "+1 (555) 201-0032",
    source: "Partner",
    status: "Nurturing",
    score: 41,
    ownerId: salesOwners[6].id,
    lastActivity: daysAgo(18),
    nextActivity: daysAhead(10),
    createdAt: daysAgo(220),
  },
  {
    id: "lead-033",
    name: "Andre Dupont",
    jobTitle: "Supply Chain VP",
    company: "Lyon Freight International",
    email: "andre.dupont@lyonfreight.example.com",
    phone: "+1 (555) 201-0033",
    source: "Outbound",
    status: "Contacted",
    score: 69,
    ownerId: salesOwners[7].id,
    lastActivity: daysAgo(5),
    nextActivity: daysAhead(4),
    createdAt: daysAgo(42),
  },
  {
    id: "lead-034",
    name: "Rebecca Osei",
    jobTitle: "Head of Talent",
    company: "Keystone HR Solutions",
    email: "rebecca.osei@keystonehr.example.com",
    source: "Referral",
    status: "New",
    score: 62,
    ownerId: salesOwners[0].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(2),
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    location: "Chicago, IL",
    timezone: "America/Chicago",
    preferredContact: "email",
    tags: ["referral"],
    activityTimeline: [
      {
        id: "a1",
        type: "creation",
        title: "Lead created",
        description: "Lead was created from a referral by Priya Raman",
        timestamp: daysAgo(1),
        actor: "System",
      },
      {
        id: "a2",
        type: "assignment",
        title: "Owner assigned to Arham Khan",
        description: "Lead was assigned based on referral source match",
        timestamp: daysAgo(1),
        actor: "System",
      },
    ],
    tasks: [
      {
        id: "t1",
        title: "Send introductory email",
        dueDate: daysAhead(0),
        status: "pending",
        priority: "high",
        ownerId: salesOwners[0].id,
      },
      {
        id: "t2",
        title: "Schedule discovery call",
        dueDate: daysAhead(2),
        status: "pending",
        priority: "medium",
        ownerId: salesOwners[0].id,
      },
    ],
    notes: [],
  },
  {
    id: "lead-035",
    name: "Victor Sanchez",
    jobTitle: "Finance Director",
    company: "Meridian Capital Partners",
    email: "victor.sanchez@meridiancap.example.com",
    phone: "+1 (555) 201-0035",
    source: "Organic Search",
    status: "Qualified",
    score: 79,
    ownerId: salesOwners[1].id,
    lastActivity: daysAgo(3),
    nextActivity: daysAhead(2),
    createdAt: daysAgo(70),
  },
  {
    id: "lead-036",
    name: "Natasha Ivanova",
    jobTitle: "VP of Product",
    company: "Crystal Analytics",
    email: "natasha.ivanova@crystalanalytics.example.com",
    source: "Paid Campaign",
    status: "Unqualified",
    score: 25,
    ownerId: salesOwners[2].id,
    lastActivity: daysAgo(40),
    nextActivity: null,
    createdAt: daysAgo(85),
  },
  {
    id: "lead-037",
    name: "Patrick Brennan",
    jobTitle: "Managing Director",
    company: "Greenfield Investments",
    email: "patrick.brennan@greenfieldinv.example.com",
    phone: "+1 (555) 201-0037",
    source: "Website",
    status: "Contacted",
    score: 71,
    ownerId: salesOwners[3].id,
    lastActivity: daysAgo(6),
    nextActivity: daysAhead(3),
    createdAt: daysAgo(55),
  },
  {
    id: "lead-038",
    name: "Keiko Yamamoto",
    jobTitle: "Engineering Manager",
    company: "Tanuki Software",
    email: "keiko.yamamoto@tanukisoft.example.com",
    phone: "+1 (555) 201-0038",
    source: "LinkedIn",
    status: "Nurturing",
    score: 44,
    ownerId: salesOwners[4].id,
    lastActivity: daysAgo(16),
    nextActivity: daysAhead(12),
    createdAt: daysAgo(195),
  },
  {
    id: "lead-039",
    name: "Gregor Schmidt",
    jobTitle: "Chief Data Officer",
    company: "Alpine Data Systems",
    email: "gregor.schmidt@alpinedata.example.com",
    source: "Event",
    status: "New",
    score: 59,
    ownerId: salesOwners[5].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(5),
    createdAt: daysAgo(9),
  },
  {
    id: "lead-040",
    name: "Monica Alvarez",
    jobTitle: "Brand Director",
    company: "Solara Cosmetics",
    email: "monica.alvarez@solara.example.com",
    phone: "+1 (555) 201-0040",
    source: "Partner",
    status: "Qualified",
    score: 86,
    ownerId: salesOwners[6].id,
    lastActivity: daysAgo(2),
    nextActivity: daysAhead(1),
    createdAt: daysAgo(60),
  },
  {
    id: "lead-041",
    name: "Thomas Eriksson",
    jobTitle: "Logistics Coordinator",
    company: "Boreal Transport",
    email: "thomas.eriksson@borealtransport.example.com",
    source: "Organic Search",
    status: "Contacted",
    score: 54,
    ownerId: salesOwners[7].id,
    lastActivity: daysAgo(9),
    nextActivity: daysAhead(6),
    createdAt: daysAgo(38),
  },
  {
    id: "lead-042",
    name: "Laura Chen",
    jobTitle: "Head of Sustainability",
    company: "TerraVerde Consulting",
    email: "laura.chen@terraverde.example.com",
    phone: "+1 (555) 201-0042",
    source: "Referral",
    status: "New",
    score: 66,
    ownerId: salesOwners[0].id,
    lastActivity: daysAgo(2),
    nextActivity: daysAhead(3),
    createdAt: daysAgo(5),
  },
  {
    id: "lead-043",
    name: "Michael Brooks",
    jobTitle: "VP of Sales",
    company: "Ironclad Security",
    email: "michael.brooks@ironcladsec.example.com",
    phone: "+1 (555) 201-0043",
    source: "Outbound",
    status: "Unqualified",
    score: 12,
    ownerId: salesOwners[1].id,
    lastActivity: daysAgo(55),
    nextActivity: null,
    createdAt: daysAgo(110),
  },
  {
    id: "lead-044",
    name: "Anastasia Petrov",
    jobTitle: "Director of Research",
    company: "Nova Pharmaceuticals",
    email: "anastasia.petrov@novapharma.example.com",
    phone: "+1 (555) 201-0044",
    source: "Paid Campaign",
    status: "Qualified",
    score: 92,
    ownerId: salesOwners[2].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(1),
    createdAt: daysAgo(30),
  },
  {
    id: "lead-045",
    name: "Christopher Lee",
    jobTitle: "CTO",
    company: "NovaByte Technologies",
    email: "christopher.lee@novabyte.example.com",
    phone: "+1 (555) 201-0045",
    source: "Website",
    status: "Nurturing",
    score: 37,
    ownerId: salesOwners[3].id,
    lastActivity: daysAgo(25),
    nextActivity: null,
    createdAt: daysAgo(250),
  },
  {
    id: "lead-046",
    name: "Priyanka Sharma",
    jobTitle: "Head of Growth",
    company: "Indus Digital",
    email: "priyanka.sharma@indusdigital.example.com",
    phone: "+1 (555) 201-0046",
    source: "LinkedIn",
    status: "Contacted",
    score: 67,
    ownerId: salesOwners[4].id,
    lastActivity: daysAgo(4),
    nextActivity: daysAhead(3),
    createdAt: daysAgo(28),
  },
  {
    id: "lead-047",
    name: "Alex Novak",
    jobTitle: "Product Design Lead",
    company: "Pixel Forge Studio",
    email: "alex.novak@pixelforge.example.com",
    source: "Event",
    status: "New",
    score: 51,
    ownerId: salesOwners[5].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(4),
    createdAt: daysAgo(3),
  },
  {
    id: "lead-048",
    name: "Hannah Wright",
    jobTitle: "Director of People",
    company: "Bloom HR Group",
    email: "hannah.wright@bloomhr.example.com",
    phone: "+1 (555) 201-0048",
    source: "Partner",
    status: "Qualified",
    score: 80,
    ownerId: salesOwners[6].id,
    lastActivity: daysAgo(2),
    nextActivity: daysAhead(2),
    createdAt: daysAgo(72),
  },
  {
    id: "lead-049",
    name: "David Park",
    jobTitle: "VP of Marketing",
    company: "Ember Creative Agency",
    email: "david.park@embercreative.example.com",
    source: "Organic Search",
    status: "Nurturing",
    score: 46,
    ownerId: salesOwners[7].id,
    lastActivity: daysAgo(15),
    nextActivity: daysAhead(8),
    createdAt: daysAgo(160),
  },
  {
    id: "lead-050",
    name: "Emma Larsson",
    jobTitle: "Chief Innovation Officer",
    company: "Polaris Tech Ventures",
    email: "emma.larsson@polaristechv.example.com",
    phone: "+1 (555) 201-0050",
    source: "Referral",
    status: "Contacted",
    score: 73,
    ownerId: salesOwners[0].id,
    lastActivity: daysAgo(5),
    nextActivity: daysAhead(2),
    createdAt: daysAgo(32),
  },
  {
    id: "lead-051",
    name: "Nathan Cooper",
    jobTitle: "Director of Partnerships",
    company: "Atlas Global Services",
    email: "nathan.cooper@atlasglobal.example.com",
    phone: "+1 (555) 201-0051",
    source: "Outbound",
    status: "New",
    score: 57,
    ownerId: salesOwners[1].id,
    lastActivity: daysAgo(2),
    nextActivity: daysAhead(5),
    createdAt: daysAgo(6),
  },
  {
    id: "lead-052",
    name: "Mila Kozlov",
    jobTitle: "R&D Director",
    company: "Quantum Leap Labs",
    email: "mila.kozlov@quantumleap.example.com",
    phone: "+1 (555) 201-0052",
    source: "Paid Campaign",
    status: "Qualified",
    score: 89,
    ownerId: salesOwners[2].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(1),
    createdAt: daysAgo(22),
  },
  {
    id: "lead-053",
    name: "Jordan Ellis",
    jobTitle: "Head of Customer Success",
    email: "jordan.ellis@example.com",
    source: "Website",
    status: "Unqualified",
    score: 19,
    ownerId: salesOwners[3].id,
    lastActivity: daysAgo(50),
    nextActivity: null,
    createdAt: daysAgo(95),
    updatedAt: daysAgo(50),
    location: "Austin, TX",
    timezone: "America/Chicago",
    preferredContact: "phone",
    tags: [],
    activityTimeline: [
      {
        id: "a1",
        type: "creation",
        title: "Lead created",
        description: "Lead was created from website contact form",
        timestamp: daysAgo(95),
        actor: "System",
      },
      {
        id: "a2",
        type: "email",
        title: "Welcome email sent",
        description: "Sent initial follow-up email after form submission",
        timestamp: daysAgo(90),
        actor: "Ethan Brooks",
        outcome: "Opened",
      },
      {
        id: "a3",
        type: "call",
        title: "Outreach call",
        description: "Called Jordan to discuss interest in our platform",
        timestamp: daysAgo(75),
        actor: "Ethan Brooks",
        outcome: "Completed",
      },
      {
        id: "a4",
        type: "email",
        title: "Product information sent",
        description: "Shared detailed product documentation and pricing after call",
        timestamp: daysAgo(74),
        actor: "Ethan Brooks",
        outcome: "Opened",
      },
      {
        id: "a5",
        type: "note",
        title: "Internal note",
        description: "Jordan is evaluating competitors. Decision timeline is unclear. May revisit next quarter.",
        timestamp: daysAgo(50),
        actor: "Ethan Brooks",
      },
      {
        id: "a6",
        type: "status_change",
        title: "Status changed to Unqualified",
        description: "Lead marked unqualified due to competitive evaluation and unclear timeline",
        timestamp: daysAgo(50),
        actor: "Ethan Brooks",
      },
    ],
    tasks: [],
    notes: [
      {
        id: "n1",
        content:
          "Jordan mentioned they are evaluating 3 competing platforms. Decision timeline is end of Q4. May revisit next quarter if they don't proceed.",
        author: "Ethan Brooks",
        createdAt: daysAgo(50),
      },
    ],
  },
  {
    id: "lead-054",
    name: "Sakura Morimoto",
    jobTitle: "Business Development",
    company: "Sakura Systems Inc",
    email: "sakura.morimoto@sakurasys.example.com",
    phone: "+1 (555) 201-0054",
    source: "Event",
    status: "Nurturing",
    score: 43,
    ownerId: salesOwners[4].id,
    lastActivity: daysAgo(20),
    nextActivity: daysAhead(10),
    createdAt: daysAgo(210),
  },
  {
    id: "lead-055",
    name: "Henry O'Brien",
    jobTitle: "VP of Engineering",
    company: "Celtic Innovation Hub",
    email: "henry.obrien@celticinnov.example.com",
    phone: "+1 (555) 201-0055",
    source: "LinkedIn",
    status: "Contacted",
    score: 64,
    ownerId: salesOwners[5].id,
    lastActivity: daysAgo(7),
    nextActivity: daysAhead(4),
    createdAt: daysAgo(40),
  },
  {
    id: "lead-056",
    name: "Diana Russo",
    jobTitle: "Chief Revenue Officer",
    company: "Apex Revenue Solutions",
    email: "diana.russo@apexrevenue.example.com",
    phone: "+1 (555) 201-0056",
    source: "Partner",
    status: "Qualified",
    score: 84,
    ownerId: salesOwners[6].id,
    lastActivity: daysAgo(2),
    nextActivity: daysAhead(1),
    createdAt: daysAgo(48),
  },
  {
    id: "lead-057",
    name: "Oscar Fernandez",
    jobTitle: "Head of Digital",
    company: "Momentum Digital Agency",
    email: "oscar.fernandez@momentumdigital.example.com",
    source: "Organic Search",
    status: "New",
    score: 53,
    ownerId: salesOwners[7].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(3),
    createdAt: daysAgo(4),
  },
  {
    id: "lead-058",
    name: "Lucia Martinelli",
    jobTitle: "Director of Strategy",
    company: "Veloce Motors Group",
    email: "lucia.martinelli@velocemotors.example.com",
    phone: "+1 (555) 201-0058",
    source: "Outbound",
    status: "Nurturing",
    score: 36,
    ownerId: salesOwners[0].id,
    lastActivity: daysAgo(30),
    nextActivity: null,
    createdAt: daysAgo(280),
  },
  {
    id: "lead-059",
    name: "Ryan Hughes",
    jobTitle: "Solutions Lead",
    company: "Apex Cloud Platform",
    email: "ryan.hughes@apexcloud.example.com",
    phone: "+1 (555) 201-0059",
    source: "Referral",
    status: "Contacted",
    score: 77,
    ownerId: salesOwners[1].id,
    lastActivity: daysAgo(3),
    nextActivity: daysAhead(2),
    createdAt: daysAgo(36),
  },
  {
    id: "lead-060",
    name: "Vanessa Cruz",
    jobTitle: "VP of Operations",
    company: "Pinnacle Operations Corp",
    email: "vanessa.cruz@pinnacleops.example.com",
    phone: "+1 (555) 201-0060",
    source: "Paid Campaign",
    status: "New",
    score: 61,
    ownerId: salesOwners[2].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(6),
    createdAt: daysAgo(8),
  },
  {
    id: "lead-061",
    name: "Ivan Petrov",
    jobTitle: "Technical Director",
    company: "Ural Engineering Works",
    email: "ivan.petrov@uraleng.example.com",
    source: "Website",
    status: "Unqualified",
    score: 14,
    ownerId: salesOwners[3].id,
    lastActivity: daysAgo(65),
    nextActivity: null,
    createdAt: daysAgo(130),
  },
  {
    id: "lead-062",
    name: "Chloe Bennett",
    jobTitle: "Head of Brand",
    company: "Stellar Branding Co",
    email: "chloe.bennett@stellarbranding.example.com",
    phone: "+1 (555) 201-0062",
    source: "LinkedIn",
    status: "Qualified",
    score: 81,
    ownerId: salesOwners[4].id,
    lastActivity: daysAgo(2),
    nextActivity: daysAhead(1),
    createdAt: daysAgo(58),
  },
  {
    id: "lead-063",
    name: "Tariq Hassan",
    jobTitle: "Director of IT",
    company: "Falcon Tech Solutions",
    email: "tariq.hassan@falcontech.example.com",
    phone: "+1 (555) 201-0063",
    source: "Event",
    status: "Nurturing",
    score: 39,
    ownerId: salesOwners[5].id,
    lastActivity: daysAgo(22),
    nextActivity: null,
    createdAt: daysAgo(230),
  },
  {
    id: "lead-064",
    name: "Rachel Kim",
    jobTitle: "VP of Sales",
    company: "Horizon Sales Partners",
    email: "rachel.kim@horizonsales.example.com",
    phone: "+1 (555) 201-0064",
    source: "Partner",
    status: "Contacted",
    score: 75,
    ownerId: salesOwners[6].id,
    lastActivity: daysAgo(4),
    nextActivity: daysAhead(2),
    createdAt: daysAgo(33),
  },
  {
    id: "lead-065",
    name: "Friedrich Weber",
    jobTitle: "Chief Operating Officer",
    company: "Munich Manufacturing GmbH",
    email: "friedrich.weber@munichmfg.example.com",
    phone: "+1 (555) 201-0065",
    source: "Organic Search",
    status: "Qualified",
    score: 93,
    ownerId: salesOwners[7].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(1),
    createdAt: daysAgo(20),
  },
  {
    id: "lead-066",
    name: "Jasmine Lee",
    jobTitle: "Director of Product",
    company: "Orchid Digital Solutions",
    email: "jasmine.lee@orchiddigital.example.com",
    phone: "+1 (555) 201-0066",
    source: "Outbound",
    status: "New",
    score: 49,
    ownerId: salesOwners[0].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(7),
    createdAt: daysAgo(2),
  },
  {
    id: "lead-067",
    name: "Antonio Costa",
    jobTitle: "Head of Sales",
    company: "Porto Tech Hub",
    email: "antonio.costa@portotech.example.com",
    source: "Referral",
    status: "Contacted",
    score: 68,
    ownerId: salesOwners[1].id,
    lastActivity: daysAgo(6),
    nextActivity: daysAhead(3),
    createdAt: daysAgo(44),
  },
  {
    id: "lead-068",
    name: "Lily Zhang",
    jobTitle: "Chief Technology Officer",
    company: "Jade Innovation Labs",
    email: "lily.zhang@jadeinnov.example.com",
    phone: "+1 (555) 201-0068",
    source: "LinkedIn",
    status: "Nurturing",
    score: 40,
    ownerId: salesOwners[2].id,
    lastActivity: daysAgo(19),
    nextActivity: daysAhead(11),
    createdAt: daysAgo(205),
  },
  {
    id: "lead-069",
    name: "Ethan Carter",
    jobTitle: "Sales Director",
    company: "Cascade Systems",
    email: "ethan.carter@cascadesys.example.com",
    phone: "+1 (555) 201-0069",
    source: "Event",
    status: "Qualified",
    score: 88,
    ownerId: salesOwners[3].id,
    lastActivity: daysAgo(2),
    nextActivity: daysAhead(1),
    createdAt: daysAgo(52),
  },
  {
    id: "lead-070",
    name: "Sophia Andersen",
    jobTitle: "VP of Partnerships",
    company: "Nordic Partners Group",
    email: "sophia.andersen@nordicpartners.example.com",
    phone: "+1 (555) 201-0070",
    source: "Paid Campaign",
    status: "New",
    score: 58,
    ownerId: salesOwners[4].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(4),
    createdAt: daysAgo(7),
  },
  {
    id: "lead-071",
    name: "Maximilian Braun",
    jobTitle: "Director of Engineering",
    company: "Berlin Digital Works",
    email: "maximilian.braun@berlindigital.example.com",
    phone: "+1 (555) 201-0071",
    source: "Website",
    status: "Unqualified",
    score: 21,
    ownerId: salesOwners[5].id,
    lastActivity: daysAgo(42),
    nextActivity: null,
    createdAt: daysAgo(100),
  },
  {
    id: "lead-072",
    name: "Olivia Hart",
    jobTitle: "Head of Customer Experience",
    company: "Harbor CX Solutions",
    email: "olivia.hart@harborcx.example.com",
    phone: "+1 (555) 201-0072",
    source: "Organic Search",
    status: "Nurturing",
    score: 34,
    ownerId: salesOwners[6].id,
    lastActivity: daysAgo(27),
    nextActivity: null,
    createdAt: daysAgo(260),
  },
  {
    id: "lead-073",
    name: "Brandon Mitchell",
    jobTitle: "VP of Business Dev",
    company: "Keystone Business Group",
    email: "brandon.mitchell@keystonebiz.example.com",
    phone: "+1 (555) 201-0073",
    source: "Partner",
    status: "Contacted",
    score: 72,
    ownerId: salesOwners[7].id,
    lastActivity: daysAgo(5),
    nextActivity: daysAhead(3),
    createdAt: daysAgo(37),
  },
  {
    id: "lead-074",
    name: "Zara Ahmed",
    jobTitle: "Director of Marketing",
    company: "Crescent Media House",
    email: "zara.ahmed@crescentmedia.example.com",
    source: "Outbound",
    status: "New",
    score: 55,
    ownerId: salesOwners[0].id,
    lastActivity: daysAgo(2),
    nextActivity: daysAhead(5),
    createdAt: daysAgo(5),
  },
  {
    id: "lead-075",
    name: "Samuel Okafor",
    jobTitle: "Head of Data",
    company: "DataSphere Analytics",
    email: "samuel.okafor@datasphere.example.com",
    phone: "+1 (555) 201-0075",
    source: "LinkedIn",
    status: "Qualified",
    score: 85,
    ownerId: salesOwners[1].id,
    lastActivity: daysAgo(2),
    nextActivity: daysAhead(1),
    createdAt: daysAgo(29),
  },
  {
    id: "lead-076",
    name: "Camille Dubois",
    jobTitle: "VP of Innovation",
    company: "Lumiere Tech Paris",
    email: "camille.dubois@lumieretech.example.com",
    phone: "+1 (555) 201-0076",
    source: "Event",
    status: "Nurturing",
    score: 47,
    ownerId: salesOwners[2].id,
    lastActivity: daysAgo(13),
    nextActivity: daysAhead(9),
    createdAt: daysAgo(170),
  },
  {
    id: "lead-077",
    name: "Jason Park",
    jobTitle: "Chief Growth Officer",
    company: "Summit Growth Partners",
    email: "jason.park@summitgrowth.example.com",
    phone: "+1 (555) 201-0077",
    source: "Referral",
    status: "Contacted",
    score: 70,
    ownerId: salesOwners[3].id,
    lastActivity: daysAgo(4),
    nextActivity: daysAhead(2),
    createdAt: daysAgo(34),
  },
  {
    id: "lead-078",
    name: "Ingrid Solberg",
    jobTitle: "Director of Sustainability",
    company: "Fjord Green Energy",
    email: "ingrid.solberg@fjordgreen.example.com",
    source: "Organic Search",
    status: "New",
    score: 50,
    ownerId: salesOwners[4].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(6),
    createdAt: daysAgo(3),
  },
  {
    id: "lead-079",
    name: "Carlos Gutierrez",
    jobTitle: "Head of Operations",
    company: "Sierra Manufacturing",
    email: "carlos.gutierrez@sierramfg.example.com",
    phone: "+1 (555) 201-0079",
    source: "Paid Campaign",
    status: "Qualified",
    score: 82,
    ownerId: salesOwners[5].id,
    lastActivity: daysAgo(3),
    nextActivity: daysAhead(2),
    createdAt: daysAgo(46),
  },
  {
    id: "lead-080",
    name: "Emily Watson",
    jobTitle: "VP of People",
    company: "Willow Creek HR",
    email: "emily.watson@willowcreekhr.example.com",
    source: "Website",
    status: "Unqualified",
    score: 16,
    ownerId: salesOwners[6].id,
    lastActivity: daysAgo(58),
    nextActivity: null,
    createdAt: daysAgo(115),
  },
  {
    id: "lead-081",
    name: "Kai Nakamura",
    jobTitle: "Director of Strategy",
    company: "Sakura Strategic Advisors",
    email: "kai.nakamura@sakurastrat.example.com",
    phone: "+1 (555) 201-0081",
    source: "Partner",
    status: "Nurturing",
    score: 42,
    ownerId: salesOwners[7].id,
    lastActivity: daysAgo(17),
    nextActivity: daysAhead(13),
    createdAt: daysAgo(190),
  },
  {
    id: "lead-082",
    name: "Natasha Romanova",
    jobTitle: "Head of Sales",
    company: "Vostok Technologies",
    email: "natasha.romanova@vostoktech.example.com",
    phone: "+1 (555) 201-0082",
    source: "Outbound",
    status: "New",
    score: 54,
    ownerId: salesOwners[0].id,
    lastActivity: daysAgo(1),
    nextActivity: daysAhead(4),
    createdAt: daysAgo(6),
  },
  {
    id: "lead-083",
    name: "Robert Chen",
    jobTitle: "Chief Financial Officer",
    company: "Pacific Financial Group",
    email: "robert.chen@pacificfin.example.com",
    phone: "+1 (555) 201-0083",
    source: "LinkedIn",
    status: "Contacted",
    score: 76,
    ownerId: salesOwners[1].id,
    lastActivity: daysAgo(3),
    nextActivity: daysAhead(2),
    createdAt: daysAgo(27),
  },
  {
    id: "lead-084",
    name: "Amara Johnson",
    jobTitle: "VP of Product",
    company: "BrightPath Innovations",
    email: "amara.johnson@brightpath.example.com",
    phone: "+1 (555) 201-0084",
    source: "Event",
    status: "Qualified",
    score: 87,
    ownerId: salesOwners[2].id,
    lastActivity: daysAgo(2),
    nextActivity: daysAhead(1),
    createdAt: daysAgo(41),
  },
  {
    id: "lead-085",
    name: "Dmitri Volkov",
    jobTitle: "Director of Engineering",
    company: "Ural Systems International",
    email: "dmitri.volkov@uralsysintl.example.com",
    source: "Referral",
    status: "Nurturing",
    score: 32,
    ownerId: salesOwners[3].id,
    lastActivity: daysAgo(32),
    nextActivity: null,
    createdAt: daysAgo(290),
  },
];

export const statusOptions: readonly LeadStatus[] = [
  "New",
  "Contacted",
  "Qualified",
  "Unqualified",
  "Nurturing",
] as const;

export const sourceOptions: readonly LeadSource[] = [
  "Website",
  "Referral",
  "LinkedIn",
  "Event",
  "Partner",
  "Outbound",
  "Organic Search",
  "Paid Campaign",
] as const;
