import { crmCompanies } from "@/app/(main)/dashboard/crm/_components/crm-data/companies";
import { salesOwners } from "@/app/(main)/dashboard/crm/_components/crm-data/sales-team";

import type {
  Company,
  CompanyActivityItem,
  CompanyDeal,
  CompanyIndustry,
  CompanyNote,
  CompanySize,
  CompanyTask,
  CompanyType,
} from "./schema";

const today = new Date(2026, 7, 16);

function daysAgo(n: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}

function timestampAgo(n: number, h = 10, m = 0): string {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  d.setHours(h, m, 0, 0);
  return `${d.toISOString().slice(0, 16)}:00.000Z`;
}

function daysFromNow(n: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}

function activity(
  id: string,
  type: CompanyActivityItem["type"],
  timestamp: string,
  subject?: string,
  description?: string,
  contactName?: string,
): CompanyActivityItem {
  const item: CompanyActivityItem = { id, type, timestamp };
  if (subject) item.subject = subject;
  if (description) item.description = description;
  if (contactName) item.contactName = contactName;
  return item;
}

function task(
  id: string,
  title: string,
  status: CompanyTask["status"],
  priority: CompanyTask["priority"],
  dueDate: string | null,
  createdAt: string,
  assigneeName?: string,
  description?: string,
): CompanyTask {
  const t: CompanyTask = { id, title, status, priority, dueDate, createdAt };
  if (assigneeName) t.assigneeName = assigneeName;
  if (description) t.description = description;
  return t;
}

function note(id: string, content: string, authorName: string, createdAt: string, updatedAt?: string): CompanyNote {
  const n: CompanyNote = { id, content, authorName, createdAt };
  if (updatedAt) n.updatedAt = updatedAt;
  return n;
}

function deal(
  id: string,
  title: string,
  value: number,
  status: CompanyDeal["status"],
  expectedCloseDate: string | null,
  createdAt: string,
): CompanyDeal {
  return { id, title, value, status, expectedCloseDate, createdAt };
}

export const companies: Company[] = [
  {
    id: crmCompanies[0].id,
    name: crmCompanies[0].name,
    domain: "asteronbio.example.com",
    industry: "Healthcare",
    type: "Customer",
    size: "501-1000",
    location: "San Francisco, CA",
    ownerId: salesOwners[0].id,
    website: "https://asteronbio.example.com",
    primaryContactId: "con-001",
    source: "Inbound",
    openDealCount: 1,
    openPipelineValue: 125000,
    wonRevenue: 210000,
    lastActivity: timestampAgo(2, 11, 0),
    tags: ["enterprise", "q1-budget"],
    description:
      "Asteron Bioworks is a biotechnology company focused on sustainable agriculture and bio-based materials. They have been a customer since Q2 2025 and recently expanded their partnership to include our enterprise analytics suite.",
    phone: "+1 (415) 555-0142",
    address: "450 Mission St, San Francisco, CA 94105",
    activityTimeline: [
      activity(
        "ca-001",
        "call",
        timestampAgo(2, 11, 0),
        "Quarterly review call",
        "Discussed Q3 goals and renewal timeline.",
        "Cameron Ruiz",
      ),
      activity(
        "ca-002",
        "email",
        timestampAgo(5, 9, 30),
        "Sent Q3 proposal",
        "Shared updated pricing for enterprise tier.",
        "Cameron Ruiz",
      ),
      activity(
        "ca-003",
        "meeting",
        timestampAgo(14, 14, 0),
        "Onsite visit",
        "Met with engineering team to review integration progress.",
        "Cameron Ruiz",
      ),
      activity(
        "ca-004",
        "note",
        timestampAgo(20, 16, 0),
        undefined,
        "Customer expressed interest in expanding to analytics module.",
        "Sofia Marchetti",
      ),
      activity(
        "ca-005",
        "call",
        timestampAgo(30, 10, 0),
        "Follow-up call",
        "Discussed onboarding timeline for new team members.",
        "Cameron Ruiz",
      ),
      activity("ca-006", "status_change", timestampAgo(365, 9, 0), undefined, "Company created", undefined),
    ],
    tasks: [
      task(
        "ct-001",
        "Send renewal proposal",
        "in_progress",
        "high",
        daysFromNow(5),
        timestampAgo(3, 14, 0),
        "Sofia Marchetti",
        "Annual renewal due Sept 15.",
      ),
      task(
        "ct-002",
        "Schedule Q4 planning meeting",
        "pending",
        "medium",
        daysFromNow(12),
        timestampAgo(2, 11, 0),
        "Cameron Ruiz",
      ),
      task(
        "ct-003",
        "Complete integration audit",
        "completed",
        "low",
        null,
        timestampAgo(30, 10, 0),
        "Ethan Brooks",
        "Audit of API usage completed.",
      ),
    ],
    notes: [
      note(
        "cn-001",
        "Cameron mentioned they are evaluating two additional products for Q4. Push the analytics bundle.",
        "Sofia Marchetti",
        timestampAgo(5, 9, 30),
      ),
      note(
        "cn-002",
        "Technical team happy with current platform. Main concern is scaling for their APAC expansion.",
        "Cameron Ruiz",
        timestampAgo(14, 14, 30),
      ),
    ],
    deals: [
      deal("cd-001", "Enterprise Analytics Bundle", 125000, "Negotiation", daysFromNow(30), timestampAgo(30, 10, 0)),
      deal("cd-002", "Base Platform Renewal", 210000, "Closed Won", null, timestampAgo(365, 9, 0)),
    ],
    createdAt: daysAgo(365),
    updatedAt: timestampAgo(2, 11, 0),
  },
  {
    id: crmCompanies[1].id,
    name: crmCompanies[1].name,
    domain: "bluehaven.example.com",
    industry: "Technology",
    type: "Customer",
    size: "201-500",
    location: "Austin, TX",
    ownerId: salesOwners[1].id,
    website: "https://bluehaven.example.com",
    primaryContactId: "con-002",
    source: "Referral",
    openDealCount: 2,
    openPipelineValue: 87500,
    wonRevenue: 64000,
    lastActivity: timestampAgo(5, 14, 0),
    tags: ["mid-market", "saas"],
    description:
      "BlueHaven Systems builds cloud-native collaboration tools for distributed teams. They were referred by Asteron Bioworks and have been a fast-growing customer since late 2024.",
    phone: "+1 (512) 555-0198",
    address: "200 Congress Ave, Austin, TX 78701",
    activityTimeline: [
      activity(
        "ca-101",
        "email",
        timestampAgo(5, 14, 0),
        "Onboarding check-in",
        "Sent onboarding completion summary to Nina.",
        "Ammar Khan",
      ),
      activity(
        "ca-102",
        "call",
        timestampAgo(12, 10, 0),
        "Technical sync",
        "Reviewed API integration status.",
        "Ammar Khan",
      ),
      activity(
        "ca-103",
        "meeting",
        timestampAgo(25, 15, 0),
        "Kick-off meeting",
        "Met with CTO and engineering leads.",
        "Ammar Khan",
      ),
      activity(
        "ca-104",
        "note",
        timestampAgo(30, 9, 0),
        undefined,
        "Nina is the key decision maker. Prefers email over calls.",
        "Ammar Khan",
      ),
      activity("ca-105", "status_change", timestampAgo(400, 9, 0), undefined, "Company created", undefined),
    ],
    tasks: [
      task(
        "ct-101",
        "Prepare Q3 usage report",
        "pending",
        "medium",
        daysFromNow(3),
        timestampAgo(2, 10, 0),
        "Ammar Khan",
      ),
      task(
        "ct-102",
        "Schedule API training session",
        "in_progress",
        "high",
        daysFromNow(7),
        timestampAgo(5, 14, 0),
        "Ammar Khan",
        "Training for their engineering team on advanced API features.",
      ),
    ],
    notes: [
      note(
        "cn-101",
        "Nina wants to expand to 3 more teams by end of year. Push the team expansion add-on.",
        "Ammar Khan",
        timestampAgo(12, 10, 30),
      ),
    ],
    deals: [
      deal("cd-101", "Platform Expansion", 45000, "Proposal", daysFromNow(21), timestampAgo(15, 10, 0)),
      deal("cd-102", "API Premium Add-on", 42500, "Qualification", daysFromNow(45), timestampAgo(5, 14, 0)),
      deal("cd-103", "Base Subscription", 64000, "Closed Won", null, timestampAgo(400, 9, 0)),
    ],
    createdAt: daysAgo(400),
    updatedAt: timestampAgo(5, 14, 0),
  },
  {
    id: crmCompanies[2].id,
    name: crmCompanies[2].name,
    domain: "cinderhealth.example.com",
    industry: "Healthcare",
    type: "Prospect",
    size: "51-200",
    location: "Boston, MA",
    ownerId: salesOwners[2].id,
    website: "https://cinderhealth.example.com",
    primaryContactId: "con-003",
    source: "Inbound",
    openDealCount: 1,
    openPipelineValue: 65000,
    wonRevenue: 0,
    lastActivity: timestampAgo(3, 10, 0),
    description:
      "Cinder Health is a digital health startup building patient engagement tools. They downloaded our whitepaper and requested a demo.",
    phone: "+1 (617) 555-0176",
    address: "100 Cambridge St, Boston, MA 02114",
    activityTimeline: [
      activity(
        "ca-201",
        "call",
        timestampAgo(3, 10, 0),
        "Demo follow-up",
        "Tomas confirmed interest in pilot program.",
        "Sofia Marchetti",
      ),
      activity(
        "ca-202",
        "meeting",
        timestampAgo(10, 14, 0),
        "Product demo",
        "Full platform demo with Tomas and two engineers.",
        "Sofia Marchetti",
      ),
      activity(
        "ca-203",
        "email",
        timestampAgo(20, 9, 0),
        "Whitepaper download",
        "Inbound lead captured from content download.",
        undefined,
      ),
    ],
    tasks: [
      task(
        "ct-201",
        "Send pilot proposal",
        "in_progress",
        "high",
        daysFromNow(2),
        timestampAgo(3, 10, 0),
        "Sofia Marchetti",
      ),
    ],
    notes: [
      note(
        "cn-201",
        "Tomas is evaluating 3 vendors. We need to move fast on the pilot proposal.",
        "Sofia Marchetti",
        timestampAgo(3, 10, 30),
      ),
    ],
    deals: [deal("cd-201", "Pilot Program", 65000, "Qualification", daysFromNow(14), timestampAgo(10, 14, 0))],
    createdAt: daysAgo(90),
    updatedAt: timestampAgo(3, 10, 0),
  },
  {
    id: crmCompanies[3].id,
    name: crmCompanies[3].name,
    domain: "driftmfg.example.com",
    industry: "Manufacturing",
    type: "Prospect",
    size: "501-1000",
    location: "Detroit, MI",
    ownerId: salesOwners[3].id,
    website: "https://driftmfg.example.com",
    primaryContactId: "con-004",
    source: "Outbound",
    openDealCount: 1,
    openPipelineValue: 42000,
    wonRevenue: 0,
    lastActivity: timestampAgo(7, 15, 0),
    tags: ["enterprise", "industrial"],
    description:
      "Drift Manufacturing produces precision industrial components. They are looking to modernize their sales operations with a CRM platform.",
    phone: "+1 (313) 555-0234",
    address: "600 Michigan Ave, Detroit, MI 48226",
    activityTimeline: [
      activity(
        "ca-301",
        "call",
        timestampAgo(7, 15, 0),
        "Qualification call",
        "Ava confirmed budget and timeline for Q1 2027.",
        "Ethan Brooks",
      ),
      activity(
        "ca-302",
        "email",
        timestampAgo(21, 10, 0),
        "Outreach email",
        "Initial cold outreach with case study.",
        undefined,
      ),
      activity("ca-303", "status_change", timestampAgo(500, 9, 0), undefined, "Company created", undefined),
    ],
    tasks: [
      task(
        "ct-301",
        "Prepare custom proposal",
        "pending",
        "high",
        daysFromNow(7),
        timestampAgo(7, 15, 0),
        "Ethan Brooks",
      ),
    ],
    notes: [
      note(
        "cn-301",
        "Ava mentioned they currently use spreadsheets. Position our platform as a comprehensive solution.",
        "Ethan Brooks",
        timestampAgo(7, 15, 30),
      ),
    ],
    deals: [deal("cd-301", "CRM Enterprise License", 42000, "Prospecting", daysFromNow(60), timestampAgo(7, 15, 0))],
    createdAt: daysAgo(500),
    updatedAt: timestampAgo(7, 15, 0),
  },
  {
    id: crmCompanies[4].id,
    name: crmCompanies[4].name,
    domain: "everline.example.com",
    industry: "Logistics",
    type: "Customer",
    size: "1001+",
    location: "São Paulo, Brazil",
    ownerId: salesOwners[4].id,
    website: "https://everline.example.com",
    primaryContactId: "con-005",
    source: "Partner",
    openDealCount: 0,
    openPipelineValue: 0,
    wonRevenue: 160000,
    lastActivity: timestampAgo(10, 10, 0),
    tags: ["logistics", "supply-chain"],
    description:
      "Everline Freight is one of South America's largest logistics providers. Partner referral through our integration with ShipLink Pro.",
    phone: "+55 (11) 5555-0142",
    address: "Av. Paulista 1578, São Paulo, SP 01310-200",
    activityTimeline: [
      activity(
        "ca-401",
        "call",
        timestampAgo(10, 10, 0),
        "Renewal check-in",
        "Mateo confirmed renewal for next year.",
        "Nadia Okafor",
      ),
      activity("ca-402", "email", timestampAgo(30, 9, 0), "Usage report", "Shared annual usage summary.", undefined),
      activity("ca-403", "status_change", timestampAgo(400, 9, 0), undefined, "Company created", undefined),
    ],
    tasks: [
      task("ct-401", "Send renewal agreement", "completed", "medium", null, timestampAgo(10, 10, 0), "Nadia Okafor"),
    ],
    notes: [
      note(
        "cn-401",
        "Mateo confirmed they will renew but wants a 10% discount for multi-year commitment.",
        "Nadia Okafor",
        timestampAgo(10, 10, 30),
      ),
    ],
    deals: [deal("cd-401", "Annual Renewal", 160000, "Closed Won", null, timestampAgo(400, 9, 0))],
    createdAt: daysAgo(400),
    updatedAt: timestampAgo(10, 10, 0),
  },
  {
    id: crmCompanies[5].id,
    name: crmCompanies[5].name,
    domain: "fieldstone.example.com",
    industry: "Financial Services",
    type: "Prospect",
    size: "51-200",
    location: "New York, NY",
    ownerId: salesOwners[0].id,
    website: "https://fieldstone.example.com",
    primaryContactId: "con-006",
    source: "Event",
    openDealCount: 1,
    openPipelineValue: 198000,
    wonRevenue: 0,
    lastActivity: timestampAgo(1, 11, 0),
    tags: ["fintech", "wealth-management"],
    description:
      "Fieldstone Capital is a boutique wealth management firm serving high-net-worth clients. Met Priya at the FinTech Summit NYC.",
    phone: "+1 (212) 555-0187",
    address: "350 Park Ave, New York, NY 10022",
    activityTimeline: [
      activity(
        "ca-501",
        "meeting",
        timestampAgo(1, 11, 0),
        "Post-event follow-up",
        "Met Priya at FinTech Summit, discussed their CRM needs.",
        "Arham Rahman",
      ),
      activity(
        "ca-502",
        "email",
        timestampAgo(3, 9, 0),
        "Follow-up email",
        "Sent deck and case study from event.",
        undefined,
      ),
      activity(
        "ca-503",
        "note",
        timestampAgo(1, 11, 30),
        undefined,
        "Very interested in compliance features. Their current CRM lacks audit trails.",
        "Arham Rahman",
      ),
    ],
    tasks: [
      task(
        "ct-501",
        "Build custom compliance demo",
        "pending",
        "high",
        daysFromNow(5),
        timestampAgo(1, 11, 0),
        "Arham Rahman",
      ),
    ],
    notes: [
      note(
        "cn-501",
        "Priya's firm manages $2B in assets. They need SOC 2 compliant CRM with full audit trails.",
        "Arham Rahman",
        timestampAgo(1, 11, 30),
      ),
    ],
    deals: [deal("cd-501", "Enterprise CRM Suite", 198000, "Qualification", daysFromNow(30), timestampAgo(1, 11, 0))],
    createdAt: daysAgo(120),
    updatedAt: timestampAgo(1, 11, 0),
  },
  {
    id: crmCompanies[6].id,
    name: crmCompanies[6].name,
    domain: "granitestudios.example.com",
    industry: "Professional Services",
    type: "Prospect",
    size: "11-50",
    location: "Portland, OR",
    ownerId: salesOwners[5].id,
    website: "https://granitestudios.example.com",
    primaryContactId: "con-007",
    source: "Website",
    openDealCount: 0,
    openPipelineValue: 0,
    wonRevenue: 0,
    lastActivity: timestampAgo(14, 10, 0),
    description:
      "Granite Studios is a boutique architecture firm exploring CRM options to manage client relationships and project pipelines.",
    activityTimeline: [
      activity(
        "ca-601",
        "email",
        timestampAgo(14, 10, 0),
        "Inquiry email",
        "Felix requested pricing information via website form.",
        undefined,
      ),
      activity(
        "ca-602",
        "note",
        timestampAgo(14, 10, 30),
        undefined,
        "Small firm, may need a simpler plan. Check if our starter tier fits.",
        "Lucas Moreau",
      ),
    ],
    tasks: [
      task("ct-601", "Send starter tier pricing", "completed", "low", null, timestampAgo(14, 10, 0), "Lucas Moreau"),
    ],
    deals: [],
    createdAt: daysAgo(45),
    updatedAt: timestampAgo(14, 10, 0),
  },
  {
    id: crmCompanies[7].id,
    name: crmCompanies[7].name,
    domain: "halcyon.example.com",
    industry: "Technology",
    type: "Former Customer",
    size: "201-500",
    location: "Seattle, WA",
    ownerId: salesOwners[6].id,
    website: "https://halcyon.example.com",
    primaryContactId: "con-008",
    source: "Inbound",
    openDealCount: 0,
    openPipelineValue: 0,
    wonRevenue: 78000,
    lastActivity: timestampAgo(120, 10, 0),
    tags: ["dormant"],
    description:
      "Halcyon Dynamics was a technology customer focused on enterprise data platforms. They churned 4 months ago citing budget constraints.",
    phone: "+1 (206) 555-0156",
    address: "999 3rd Ave, Seattle, WA 98104",
    activityTimeline: [
      activity(
        "ca-701",
        "call",
        timestampAgo(120, 10, 0),
        "Offboarding call",
        "Hana confirmed churn due to budget cuts.",
        "Isla Grant",
      ),
      activity(
        "ca-702",
        "email",
        timestampAgo(90, 9, 0),
        "Win-back campaign",
        "Sent re-engagement email with new pricing.",
        undefined,
      ),
      activity(
        "ca-703",
        "status_change",
        timestampAgo(120, 10, 0),
        undefined,
        "Status changed to Former Customer",
        undefined,
      ),
      activity("ca-704", "status_change", timestampAgo(500, 9, 0), undefined, "Company created", undefined),
    ],
    tasks: [
      task(
        "ct-701",
        "Schedule win-back call",
        "pending",
        "medium",
        daysFromNow(30),
        timestampAgo(90, 9, 0),
        "Isla Grant",
        "Follow up with Hana about new pricing options.",
      ),
    ],
    notes: [
      note(
        "cn-701",
        "Hana mentioned they might revisit in Q1 2027 if budget improves. Keep them on the win-back list.",
        "Isla Grant",
        timestampAgo(120, 10, 30),
      ),
    ],
    deals: [deal("cd-701", "Original License", 78000, "Closed Won", null, timestampAgo(500, 9, 0))],
    archivedAt: daysAgo(45),
    archivedBy: "arham",
    createdAt: daysAgo(500),
    updatedAt: timestampAgo(120, 10, 0),
  },
  {
    id: crmCompanies[8].id,
    name: crmCompanies[8].name,
    domain: "ironcrest.example.com",
    industry: "Financial Services",
    type: "Prospect",
    size: "51-200",
    location: "Dubai, UAE",
    ownerId: salesOwners[7].id,
    website: "https://ironcrest.example.com",
    primaryContactId: "con-009",
    source: "Referral",
    openDealCount: 1,
    openPipelineValue: 340000,
    wonRevenue: 0,
    lastActivity: timestampAgo(1, 11, 0),
    tags: ["venture-capital", "international"],
    description:
      "Ironcrest Ventures is a Dubai-based venture capital firm. Referred by Fieldstone Capital. Looking for an enterprise CRM with multi-entity support.",
    phone: "+971 4 555 0198",
    address: "DIFC Gate Village, Dubai, UAE",
    activityTimeline: [
      activity(
        "ca-801",
        "call",
        timestampAgo(1, 11, 0),
        "Discovery call",
        "Omar outlined their multi-entity requirements.",
        "Kenji Nakamura",
      ),
      activity(
        "ca-802",
        "email",
        timestampAgo(4, 9, 0),
        "Referral introduction",
        "Warm intro from Fieldstone Capital.",
        undefined,
      ),
    ],
    tasks: [
      task(
        "ct-801",
        "Prepare multi-entity demo",
        "pending",
        "high",
        daysFromNow(4),
        timestampAgo(1, 11, 0),
        "Kenji Nakamura",
      ),
    ],
    notes: [
      note(
        "cn-801",
        "Omar manages 3 entities across UAE, UK, and Singapore. Needs consolidated reporting.",
        "Kenji Nakamura",
        timestampAgo(1, 11, 30),
      ),
    ],
    deals: [
      deal("cd-801", "Enterprise Multi-Entity", 340000, "Qualification", daysFromNow(45), timestampAgo(1, 11, 0)),
    ],
    createdAt: daysAgo(150),
    updatedAt: timestampAgo(1, 11, 0),
  },
  {
    id: crmCompanies[9].id,
    name: crmCompanies[9].name,
    domain: "juniper.example.com",
    industry: "Technology",
    type: "Prospect",
    size: "201-500",
    location: "Warsaw, Poland",
    ownerId: salesOwners[1].id,
    website: "https://juniper.example.com",
    primaryContactId: "con-010",
    source: "Inbound",
    openDealCount: 0,
    openPipelineValue: 0,
    wonRevenue: 0,
    lastActivity: null,
    tags: ["enterprise", "infrastructure"],
    description:
      "Juniper Infrastructure provides cloud infrastructure services across Central Europe. They filled out a contact form but have not responded to follow-ups.",
    activityTimeline: [
      activity(
        "ca-901",
        "email",
        timestampAgo(10, 9, 0),
        "Follow-up email",
        "Second follow-up after no response.",
        undefined,
      ),
      activity(
        "ca-902",
        "email",
        timestampAgo(18, 9, 0),
        "Initial outreach",
        "Responded to their website inquiry.",
        undefined,
      ),
    ],
    tasks: [
      task(
        "ct-901",
        "Third follow-up attempt",
        "pending",
        "low",
        daysFromNow(10),
        timestampAgo(10, 9, 0),
        "Ammar Khan",
      ),
    ],
    deals: [],
    createdAt: daysAgo(10),
  },
  {
    id: crmCompanies[10].id,
    name: crmCompanies[10].name,
    domain: "kestrel.example.com",
    industry: "Retail",
    type: "Prospect",
    size: "51-200",
    location: "Barcelona, Spain",
    ownerId: salesOwners[2].id,
    website: "https://kestrel.example.com",
    primaryContactId: "con-011",
    source: "Outbound",
    openDealCount: 0,
    openPipelineValue: 0,
    wonRevenue: 0,
    lastActivity: timestampAgo(21, 14, 0),
    tags: ["ecommerce", "retail"],
    description:
      "Kestrel Commerce is an online retailer specializing in outdoor gear. Outbound prospect but went cold after initial outreach.",
    phone: "+34 93 555 0132",
    address: "Passeig de Gràcia 50, Barcelona, Spain",
    activityTimeline: [
      activity(
        "ca-a01",
        "call",
        timestampAgo(21, 14, 0),
        "Cold call",
        "Rosa answered but said they are busy with peak season.",
        "Sofia Marchetti",
      ),
      activity(
        "ca-a02",
        "email",
        timestampAgo(35, 9, 0),
        "Outbound email",
        "Sent introductory email with ecommerce case study.",
        undefined,
      ),
    ],
    tasks: [],
    deals: [],
    createdAt: daysAgo(30),
    updatedAt: timestampAgo(21, 14, 0),
  },
  {
    id: crmCompanies[11].id,
    name: crmCompanies[11].name,
    domain: "lattice.example.com",
    industry: "Healthcare",
    type: "Customer",
    size: "201-500",
    location: "Zurich, Switzerland",
    ownerId: salesOwners[0].id,
    website: "https://lattice.example.com",
    primaryContactId: "con-012",
    source: "Partner",
    openDealCount: 1,
    openPipelineValue: 89000,
    wonRevenue: 134000,
    lastActivity: timestampAgo(3, 14, 0),
    tags: ["vip", "renewal-march"],
    description:
      "Lattice Clinical is a Swiss healthcare analytics company. VIP customer with dedicated account manager. Annual renewal in March.",
    phone: "+41 44 555 0187",
    address: "Bahnhofstrasse 42, Zurich, Switzerland",
    activityTimeline: [
      activity(
        "ca-b01",
        "meeting",
        timestampAgo(3, 14, 0),
        "Q3 planning",
        "Reviewed their analytics dashboard usage and expansion opportunities.",
        "Arham Rahman",
      ),
      activity(
        "ca-b02",
        "call",
        timestampAgo(15, 10, 0),
        "Renewal discussion",
        "Jonas wants to lock in current pricing for 2 years.",
        "Arham Rahman",
      ),
      activity(
        "ca-b03",
        "email",
        timestampAgo(25, 9, 0),
        "Usage insights",
        "Shared their team's usage analytics.",
        undefined,
      ),
    ],
    tasks: [
      task(
        "ct-b01",
        "Draft 2-year renewal proposal",
        "in_progress",
        "high",
        daysFromNow(3),
        timestampAgo(3, 14, 0),
        "Arham Rahman",
      ),
    ],
    notes: [
      note(
        "cn-b01",
        "Jonas is very satisfied. Main request is better reporting for their compliance team.",
        "Arham Rahman",
        timestampAgo(3, 14, 30),
      ),
    ],
    deals: [
      deal("cd-b01", "2-Year Renewal + Analytics", 89000, "Proposal", daysFromNow(10), timestampAgo(3, 14, 0)),
      deal("cd-b02", "Original License", 134000, "Closed Won", null, timestampAgo(280, 9, 0)),
    ],
    createdAt: daysAgo(280),
    updatedAt: timestampAgo(3, 14, 0),
  },
  {
    id: crmCompanies[12].id,
    name: crmCompanies[12].name,
    domain: "marinerfoods.example.com",
    industry: "Hospitality",
    type: "Customer",
    size: "1001+",
    location: "Paris, France",
    ownerId: salesOwners[3].id,
    website: "https://marinerfoods.example.com",
    primaryContactId: "con-013",
    source: "Event",
    openDealCount: 2,
    openPipelineValue: 156000,
    wonRevenue: 92000,
    lastActivity: timestampAgo(4, 10, 0),
    tags: ["food-production", "distribution"],
    description:
      "Mariner Foods is a large food production and distribution company operating across Europe. Met Claire at the Paris Food Expo.",
    phone: "+33 1 55 55 0142",
    address: "15 Rue de Rivoli, Paris, France",
    activityTimeline: [
      activity(
        "ca-c01",
        "call",
        timestampAgo(4, 10, 0),
        "Product discussion",
        "Claire wants to add distribution tracking module.",
        "Ethan Brooks",
      ),
      activity(
        "ca-c02",
        "meeting",
        timestampAgo(12, 14, 0),
        "Onsite visit",
        "Visited their Paris HQ to review integration needs.",
        "Ethan Brooks",
      ),
      activity(
        "ca-c03",
        "email",
        timestampAgo(20, 9, 0),
        "Distribution module specs",
        "Sent technical specifications for the new module.",
        undefined,
      ),
    ],
    tasks: [
      task(
        "ct-c01",
        "Send distribution module proposal",
        "in_progress",
        "high",
        daysFromNow(2),
        timestampAgo(4, 10, 0),
        "Ethan Brooks",
      ),
      task(
        "ct-c02",
        "Schedule training for EU team",
        "pending",
        "medium",
        daysFromNow(14),
        timestampAgo(4, 10, 0),
        "Ethan Brooks",
      ),
    ],
    notes: [
      note(
        "cn-c01",
        "Claire is pushing for Q4 launch of distribution tracking. Need to fast-track the proposal.",
        "Ethan Brooks",
        timestampAgo(4, 10, 30),
      ),
    ],
    deals: [
      deal("cd-c01", "Distribution Module", 98000, "Negotiation", daysFromNow(15), timestampAgo(12, 14, 0)),
      deal("cd-c02", "Analytics Add-on", 58000, "Prospecting", daysFromNow(45), timestampAgo(4, 10, 0)),
      deal("cd-c03", "Base Platform", 92000, "Closed Won", null, timestampAgo(320, 9, 0)),
    ],
    createdAt: daysAgo(320),
    updatedAt: timestampAgo(4, 10, 0),
  },
  {
    id: crmCompanies[13].id,
    name: crmCompanies[13].name,
    domain: "northfield.example.com",
    industry: "Manufacturing",
    type: "Prospect",
    size: "501-1000",
    location: "Houston, TX",
    ownerId: salesOwners[4].id,
    website: "https://northfield.example.com",
    primaryContactId: "con-014",
    source: "Outbound",
    openDealCount: 1,
    openPipelineValue: 72000,
    wonRevenue: 0,
    lastActivity: timestampAgo(2, 11, 0),
    tags: ["energy", "renewables"],
    description:
      "Northfield Energy operates in the renewable energy sector. Samira is evaluating CRM solutions for their growing field operations team.",
    phone: "+1 (713) 555-0198",
    address: "1200 McKinney St, Houston, TX 77010",
    activityTimeline: [
      activity(
        "ca-d01",
        "call",
        timestampAgo(2, 11, 0),
        "Demo request",
        "Samira requested a demo focused on field team management.",
        "Nadia Okafor",
      ),
      activity(
        "ca-d02",
        "email",
        timestampAgo(8, 9, 0),
        "Outreach email",
        "Sent case study about energy sector CRM adoption.",
        undefined,
      ),
    ],
    tasks: [
      task(
        "ct-d01",
        "Prepare field team demo",
        "pending",
        "high",
        daysFromNow(3),
        timestampAgo(2, 11, 0),
        "Nadia Okafor",
      ),
    ],
    notes: [
      note(
        "cn-d01",
        "Samira needs mobile-first CRM for their field reps. Highlight our mobile app capabilities.",
        "Nadia Okafor",
        timestampAgo(2, 11, 30),
      ),
    ],
    deals: [deal("cd-d01", "Field Operations CRM", 72000, "Prospecting", daysFromNow(30), timestampAgo(2, 11, 0))],
    createdAt: daysAgo(60),
    updatedAt: timestampAgo(2, 11, 0),
  },
  {
    id: crmCompanies[14].id,
    name: crmCompanies[14].name,
    domain: "quantumleap.example.com",
    industry: "Technology",
    type: "Prospect",
    size: "51-200",
    location: "Cambridge, MA",
    ownerId: salesOwners[2].id,
    website: "https://quantumleap.example.com",
    primaryContactId: "con-072",
    source: "Website",
    openDealCount: 0,
    openPipelineValue: 0,
    wonRevenue: 0,
    lastActivity: timestampAgo(18, 14, 0),
    tags: ["ai", "startup"],
    description:
      "Quantum Leap Labs is an AI research startup. They signed up for a free trial but haven't converted yet.",
    activityTimeline: [
      activity(
        "ca-e01",
        "email",
        timestampAgo(18, 14, 0),
        "Trial follow-up",
        "Sent trial usage tips and offered a call.",
        undefined,
      ),
      activity(
        "ca-e02",
        "note",
        timestampAgo(20, 9, 0),
        undefined,
        "Derek signed up for trial. Company is pre-Series A.",
        "Sofia Marchetti",
      ),
    ],
    tasks: [],
    deals: [],
    createdAt: daysAgo(22),
    updatedAt: timestampAgo(18, 14, 0),
  },
  {
    id: crmCompanies[15].id,
    name: crmCompanies[15].name,
    domain: "summitconstr.example.com",
    industry: "Real Estate",
    type: "Former Customer",
    size: "201-500",
    location: "Denver, CO",
    ownerId: salesOwners[3].id,
    website: "https://summitconstr.example.com",
    primaryContactId: "con-073",
    source: "Referral",
    openDealCount: 0,
    openPipelineValue: 0,
    wonRevenue: 45000,
    lastActivity: timestampAgo(90, 9, 0),
    tags: ["construction", "dormant"],
    description:
      "Summit Construction is a mid-size construction company. Churned after their project-based needs didn't match our platform strengths.",
    activityTimeline: [
      activity(
        "ca-f01",
        "call",
        timestampAgo(90, 9, 0),
        "Offboarding call",
        "Aisha confirmed they are switching to a construction-specific tool.",
        "Ethan Brooks",
      ),
      activity(
        "ca-f02",
        "status_change",
        timestampAgo(90, 9, 0),
        undefined,
        "Status changed to Former Customer",
        undefined,
      ),
      activity("ca-f03", "status_change", timestampAgo(340, 9, 0), undefined, "Company created", undefined),
    ],
    tasks: [],
    notes: [
      note(
        "cn-f01",
        "Aisha said if we add construction-specific features in the future, they would reconsider.",
        "Ethan Brooks",
        timestampAgo(90, 9, 30),
      ),
    ],
    deals: [deal("cd-f01", "Original License", 45000, "Closed Won", null, timestampAgo(340, 9, 0))],
    archivedAt: daysAgo(30),
    archivedBy: "ammar",
    createdAt: daysAgo(340),
    updatedAt: timestampAgo(90, 9, 0),
  },
  {
    id: crmCompanies[16].id,
    name: crmCompanies[16].name,
    domain: "novapharma.example.com",
    industry: "Healthcare",
    type: "Customer",
    size: "501-1000",
    location: "Basel, Switzerland",
    ownerId: salesOwners[6].id,
    website: "https://novapharma.example.com",
    primaryContactId: "con-074",
    source: "Partner",
    openDealCount: 2,
    openPipelineValue: 185000,
    wonRevenue: 120000,
    lastActivity: timestampAgo(1, 10, 0),
    tags: ["pharma", "international", "enterprise"],
    description:
      "Nova Pharmaceuticals is a global pharma company with operations in 12 countries. Partner referral through MedTech Alliance.",
    phone: "+41 61 555 0198",
    address: "Hochbergerstrasse 60C, Basel, Switzerland",
    activityTimeline: [
      activity(
        "ca-g01",
        "call",
        timestampAgo(1, 10, 0),
        "Expansion discussion",
        "Liam wants to roll out to APAC offices.",
        "Isla Grant",
      ),
      activity(
        "ca-g02",
        "meeting",
        timestampAgo(8, 14, 0),
        "Q3 review",
        "Reviewed platform usage across 6 offices.",
        "Isla Grant",
      ),
      activity(
        "ca-g03",
        "email",
        timestampAgo(15, 9, 0),
        "APAC rollout plan",
        "Shared rollout timeline and pricing.",
        undefined,
      ),
    ],
    tasks: [
      task(
        "ct-g01",
        "Finalize APAC pricing",
        "in_progress",
        "high",
        daysFromNow(2),
        timestampAgo(1, 10, 0),
        "Isla Grant",
      ),
      task(
        "ct-g02",
        "Schedule APAC team training",
        "pending",
        "medium",
        daysFromNow(20),
        timestampAgo(8, 14, 0),
        "Isla Grant",
      ),
    ],
    notes: [
      note(
        "cn-g01",
        "Liam needs the APAC rollout to be live before their fiscal year ends in March. Tight timeline.",
        "Isla Grant",
        timestampAgo(1, 10, 30),
      ),
    ],
    deals: [
      deal("cd-g01", "APAC Expansion", 120000, "Proposal", daysFromNow(14), timestampAgo(8, 14, 0)),
      deal("cd-g02", "Compliance Module", 65000, "Qualification", daysFromNow(30), timestampAgo(1, 10, 0)),
      deal("cd-g03", "Base Platform (EMEA)", 120000, "Closed Won", null, timestampAgo(520, 9, 0)),
    ],
    createdAt: daysAgo(520),
    updatedAt: timestampAgo(1, 10, 0),
  },
  {
    id: crmCompanies[17].id,
    name: crmCompanies[17].name,
    domain: "fjordmedia.example.com",
    industry: "Professional Services",
    type: "Prospect",
    size: "11-50",
    location: "Oslo, Norway",
    ownerId: salesOwners[1].id,
    website: "https://fjordmedia.example.com",
    primaryContactId: "con-075",
    source: "Website",
    openDealCount: 0,
    openPipelineValue: 0,
    wonRevenue: 0,
    lastActivity: timestampAgo(4, 9, 0),
    tags: ["media", "international"],
    description:
      "Fjord Media Group is a small media production company in Norway. Emma filled out a demo request form.",
    activityTimeline: [
      activity(
        "ca-h01",
        "email",
        timestampAgo(4, 9, 0),
        "Demo request response",
        "Sent demo scheduling link to Emma.",
        undefined,
      ),
    ],
    tasks: [
      task(
        "ct-h01",
        "Schedule demo with Emma",
        "pending",
        "medium",
        daysFromNow(5),
        timestampAgo(4, 9, 0),
        "Ammar Khan",
      ),
    ],
    deals: [],
    createdAt: daysAgo(4),
  },
  {
    id: crmCompanies[18].id,
    name: crmCompanies[18].name,
    domain: "apexindustrial.example.com",
    industry: "Manufacturing",
    type: "Customer",
    size: "501-1000",
    location: "Pittsburgh, PA",
    ownerId: salesOwners[5].id,
    website: "https://apexindustrial.example.com",
    primaryContactId: "con-076",
    source: "Inbound",
    openDealCount: 1,
    openPipelineValue: 68000,
    wonRevenue: 145000,
    lastActivity: timestampAgo(3, 10, 0),
    tags: ["manufacturing", "industrial"],
    description:
      "Apex Industrial manufactures precision parts for the aerospace and defense industry. Long-standing customer with consistent expansion.",
    phone: "+1 (412) 555-0176",
    address: "500 Liberty Ave, Pittsburgh, PA 15222",
    activityTimeline: [
      activity(
        "ca-i01",
        "call",
        timestampAgo(3, 10, 0),
        "Upsell discussion",
        "Carlos interested in quality management module.",
        "Lucas Moreau",
      ),
      activity(
        "ca-i02",
        "email",
        timestampAgo(10, 9, 0),
        "Monthly report",
        "Sent their monthly platform usage report.",
        undefined,
      ),
    ],
    tasks: [
      task("ct-i01", "Send QM module specs", "pending", "high", daysFromNow(3), timestampAgo(3, 10, 0), "Lucas Moreau"),
    ],
    notes: [
      note(
        "cn-i01",
        "Carlos is evaluating QM modules from 3 vendors. Our advantage is the existing integration.",
        "Lucas Moreau",
        timestampAgo(3, 10, 30),
      ),
    ],
    deals: [
      deal("cd-i01", "Quality Management Module", 68000, "Negotiation", daysFromNow(14), timestampAgo(3, 10, 0)),
      deal("cd-i02", "Base Platform", 145000, "Closed Won", null, timestampAgo(410, 9, 0)),
    ],
    createdAt: daysAgo(410),
    updatedAt: timestampAgo(3, 10, 0),
  },
  {
    id: crmCompanies[19].id,
    name: crmCompanies[19].name,
    domain: "sakurabio.example.com",
    industry: "Healthcare",
    type: "Customer",
    size: "201-500",
    location: "Tokyo, Japan",
    ownerId: salesOwners[4].id,
    website: "https://sakurabio.example.com",
    primaryContactId: "con-077",
    source: "Partner",
    openDealCount: 1,
    openPipelineValue: 82000,
    wonRevenue: 56000,
    lastActivity: timestampAgo(2, 11, 0),
    tags: ["biotech", "international"],
    description:
      "Sakura Biomedical is a Japanese biotech firm focused on regenerative medicine. Partner referral through BioConnect Asia.",
    phone: "+81 3 5555 0142",
    address: "Marunouchi 1-9-2, Tokyo, Japan",
    activityTimeline: [
      activity(
        "ca-j01",
        "call",
        timestampAgo(2, 11, 0),
        "Quarterly check-in",
        "Yuki discussed expanding to their Seoul office.",
        "Nadia Okafor",
      ),
      activity(
        "ca-j02",
        "email",
        timestampAgo(12, 9, 0),
        "Feature request",
        "Requested Japanese language support for their team.",
        undefined,
      ),
    ],
    tasks: [
      task(
        "ct-j01",
        "Check Japanese localization timeline",
        "pending",
        "medium",
        daysFromNow(7),
        timestampAgo(2, 11, 0),
        "Nadia Okafor",
      ),
    ],
    notes: [
      note(
        "cn-j01",
        "Yuki's team is growing fast. They need Japanese language support to onboard their full team.",
        "Nadia Okafor",
        timestampAgo(2, 11, 30),
      ),
    ],
    deals: [
      deal("cd-j01", "Seoul Office Expansion", 82000, "Qualification", daysFromNow(30), timestampAgo(2, 11, 0)),
      deal("cd-j02", "Base Platform", 56000, "Closed Won", null, timestampAgo(290, 9, 0)),
    ],
    createdAt: daysAgo(290),
    updatedAt: timestampAgo(2, 11, 0),
  },
  {
    id: crmCompanies[20].id,
    name: crmCompanies[20].name,
    domain: "polaristechv.example.com",
    industry: "Technology",
    type: "Prospect",
    size: "11-50",
    location: "Helsinki, Finland",
    ownerId: salesOwners[0].id,
    website: "https://polaristechv.example.com",
    primaryContactId: "con-078",
    source: "Event",
    openDealCount: 1,
    openPipelineValue: 35000,
    wonRevenue: 0,
    lastActivity: timestampAgo(1, 11, 0),
    tags: ["startup", "international"],
    description:
      "Polaris Tech Ventures is a Finnish startup accelerator. Mikko met Arham at Slush Helsinki and is evaluating CRM for their portfolio companies.",
    phone: "+358 9 555 0187",
    address: "Kaivokatu 8, Helsinki, Finland",
    activityTimeline: [
      activity(
        "ca-k01",
        "meeting",
        timestampAgo(1, 11, 0),
        "Slush follow-up",
        "Met Mikko at Slush, discussed portfolio-wide CRM deployment.",
        "Arham Rahman",
      ),
      activity(
        "ca-k02",
        "email",
        timestampAgo(3, 9, 0),
        "Post-event email",
        "Sent deck with portfolio pricing model.",
        undefined,
      ),
    ],
    tasks: [
      task(
        "ct-k01",
        "Build portfolio pricing model",
        "in_progress",
        "high",
        daysFromNow(5),
        timestampAgo(1, 11, 0),
        "Arham Rahman",
      ),
    ],
    notes: [
      note(
        "cn-k01",
        "Mikko wants to offer CRM as a benefit to their 15 portfolio companies. Could be a large deal if structured right.",
        "Arham Rahman",
        timestampAgo(1, 11, 30),
      ),
    ],
    deals: [deal("cd-k01", "Portfolio CRM Package", 35000, "Qualification", daysFromNow(21), timestampAgo(1, 11, 0))],
    createdAt: daysAgo(32),
    updatedAt: timestampAgo(1, 11, 0),
  },
  {
    id: crmCompanies[21].id,
    name: crmCompanies[21].name,
    domain: "momentumdigital.example.com",
    industry: "Professional Services",
    type: "Prospect",
    size: "11-50",
    location: "Barcelona, Spain",
    ownerId: salesOwners[7].id,
    website: "https://momentumdigital.example.com",
    primaryContactId: "con-079",
    source: "Website",
    openDealCount: 0,
    openPipelineValue: 0,
    wonRevenue: 0,
    lastActivity: timestampAgo(4, 9, 0),
    tags: ["digital-agency", "international"],
    description:
      "Momentum Digital Agency is a small digital marketing agency. Sara submitted a contact form asking about pricing.",
    activityTimeline: [
      activity(
        "ca-l01",
        "email",
        timestampAgo(4, 9, 0),
        "Pricing inquiry",
        "Sara asked about agency-tier pricing.",
        undefined,
      ),
    ],
    tasks: [
      task(
        "ct-l01",
        "Send agency pricing sheet",
        "pending",
        "low",
        daysFromNow(7),
        timestampAgo(4, 9, 0),
        "Kenji Nakamura",
      ),
    ],
    deals: [],
    createdAt: daysAgo(4),
  },
  {
    id: crmCompanies[22].id,
    name: crmCompanies[22].name,
    domain: "cascadesys.example.com",
    industry: "Technology",
    type: "Customer",
    size: "201-500",
    location: "Vancouver, BC",
    ownerId: salesOwners[3].id,
    website: "https://cascadesys.example.com",
    primaryContactId: "con-080",
    source: "Inbound",
    openDealCount: 1,
    openPipelineValue: 52000,
    wonRevenue: 88000,
    lastActivity: timestampAgo(5, 10, 0),
    tags: ["cloud", "saas"],
    description:
      "Cascade Systems provides cloud infrastructure management tools. Jordan is evaluating additional modules for their growing team.",
    phone: "+1 (604) 555-0198",
    address: "1055 W Georgia St, Vancouver, BC V6E 3R3",
    activityTimeline: [
      activity(
        "ca-m01",
        "call",
        timestampAgo(5, 10, 0),
        "Feature review",
        "Jordan asked about advanced reporting features.",
        "Ethan Brooks",
      ),
      activity("ca-m02", "email", timestampAgo(15, 9, 0), "Usage report", "Shared monthly usage analytics.", undefined),
    ],
    tasks: [
      task(
        "ct-m01",
        "Schedule reporting demo",
        "pending",
        "medium",
        daysFromNow(5),
        timestampAgo(5, 10, 0),
        "Ethan Brooks",
      ),
    ],
    notes: [
      note(
        "cn-m01",
        "Jordan wants to consolidate their tools. Our reporting module could replace their current BI tool.",
        "Ethan Brooks",
        timestampAgo(5, 10, 30),
      ),
    ],
    deals: [
      deal("cd-m01", "Reporting Module", 52000, "Proposal", daysFromNow(14), timestampAgo(5, 10, 0)),
      deal("cd-m02", "Base Platform", 88000, "Closed Won", null, timestampAgo(310, 9, 0)),
    ],
    createdAt: daysAgo(310),
    updatedAt: timestampAgo(5, 10, 0),
  },
  {
    id: crmCompanies[23].id,
    name: crmCompanies[23].name,
    domain: "velocemotors.example.com",
    industry: "Manufacturing",
    type: "Former Customer",
    size: "1001+",
    location: "Munich, Germany",
    ownerId: salesOwners[0].id,
    website: "https://velocemotors.example.com",
    primaryContactId: "con-081",
    source: "Partner",
    openDealCount: 0,
    openPipelineValue: 0,
    wonRevenue: 210000,
    lastActivity: timestampAgo(120, 9, 0),
    tags: ["automotive", "international", "dormant"],
    description:
      "Veloce Motors Group is a German automotive manufacturer. Was a large customer but churned after a merger changed their vendor strategy.",
    phone: "+49 89 555 0176",
    address: "Leopoldstrasse 10, Munich, Germany",
    activityTimeline: [
      activity(
        "ca-n01",
        "call",
        timestampAgo(120, 9, 0),
        "Churn call",
        "Marco explained the merger changed their vendor contracts.",
        "Arham Rahman",
      ),
      activity(
        "ca-n02",
        "status_change",
        timestampAgo(120, 9, 0),
        undefined,
        "Status changed to Former Customer",
        undefined,
      ),
      activity("ca-n03", "status_change", timestampAgo(550, 9, 0), undefined, "Company created", undefined),
    ],
    tasks: [],
    notes: [
      note(
        "cn-n01",
        "Marco said the merger brought in a new procurement team that standardized on a different vendor. Unlikely to return.",
        "Arham Rahman",
        timestampAgo(120, 9, 30),
      ),
    ],
    deals: [deal("cd-n01", "Original Enterprise License", 210000, "Closed Won", null, timestampAgo(550, 9, 0))],
    archivedAt: daysAgo(20),
    archivedBy: "sofia",
    createdAt: daysAgo(550),
    updatedAt: timestampAgo(120, 9, 0),
  },
  {
    id: crmCompanies[24].id,
    name: crmCompanies[24].name,
    domain: "terraverde.example.com",
    industry: "Professional Services",
    type: "Prospect",
    size: "11-50",
    location: "San Francisco, CA",
    ownerId: salesOwners[2].id,
    website: "https://terraverde.example.com",
    primaryContactId: "con-082",
    source: "Referral",
    openDealCount: 1,
    openPipelineValue: 28000,
    wonRevenue: 0,
    lastActivity: timestampAgo(3, 11, 0),
    tags: ["sustainability", "consulting"],
    description:
      "TerraVerde Consulting advises companies on sustainability practices. Nina was referred by a mutual contact at a sustainability conference.",
    phone: "+1 (415) 555-0132",
    address: "1 Market St, San Francisco, CA 94105",
    activityTimeline: [
      activity(
        "ca-o01",
        "call",
        timestampAgo(3, 11, 0),
        "Introductory call",
        "Nina is looking for a simple CRM for her 20-person team.",
        "Sofia Marchetti",
      ),
      activity(
        "ca-o02",
        "email",
        timestampAgo(5, 9, 0),
        "Referral introduction",
        "Warm intro from mutual contact.",
        undefined,
      ),
    ],
    tasks: [
      task(
        "ct-o01",
        "Send starter tier proposal",
        "pending",
        "medium",
        daysFromNow(3),
        timestampAgo(3, 11, 0),
        "Sofia Marchetti",
      ),
    ],
    notes: [
      note(
        "cn-o01",
        "Nina's firm is growing. She wants something easy to use with good email integration.",
        "Sofia Marchetti",
        timestampAgo(3, 11, 30),
      ),
    ],
    deals: [deal("cd-o01", "Starter Tier Annual", 28000, "Qualification", daysFromNow(14), timestampAgo(3, 11, 0))],
    createdAt: daysAgo(5),
    updatedAt: timestampAgo(3, 11, 0),
  },
  {
    id: crmCompanies[25].id,
    name: crmCompanies[25].name,
    domain: "datasphere.example.com",
    industry: "Technology",
    type: "Customer",
    size: "51-200",
    location: "Toronto, ON",
    ownerId: salesOwners[1].id,
    website: "https://datasphere.example.com",
    primaryContactId: "con-083",
    source: "Inbound",
    openDealCount: 1,
    openPipelineValue: 42000,
    wonRevenue: 65000,
    lastActivity: timestampAgo(4, 10, 0),
    tags: ["analytics", "data"],
    description:
      "DataSphere Analytics provides business intelligence tools. Aiden signed up through our website and converted to a paid plan.",
    phone: "+1 (416) 555-0187",
    address: "100 King St W, Toronto, ON M5X 1C9",
    activityTimeline: [
      activity(
        "ca-p01",
        "call",
        timestampAgo(4, 10, 0),
        "Upsell call",
        "Aiden interested in advanced analytics features.",
        "Ammar Khan",
      ),
      activity(
        "ca-p02",
        "email",
        timestampAgo(12, 9, 0),
        "Onboarding complete",
        "Confirmed full team onboarding is done.",
        undefined,
      ),
    ],
    tasks: [
      task(
        "ct-p01",
        "Send advanced analytics demo link",
        "pending",
        "medium",
        daysFromNow(5),
        timestampAgo(4, 10, 0),
        "Ammar Khan",
      ),
    ],
    notes: [
      note(
        "cn-p01",
        "Aiden's team has fully adopted the platform. Good candidate for advanced tier upgrade.",
        "Ammar Khan",
        timestampAgo(4, 10, 30),
      ),
    ],
    deals: [
      deal("cd-p01", "Advanced Analytics Add-on", 42000, "Proposal", daysFromNow(14), timestampAgo(4, 10, 0)),
      deal("cd-p02", "Base Platform", 65000, "Closed Won", null, timestampAgo(220, 9, 0)),
    ],
    createdAt: daysAgo(220),
    updatedAt: timestampAgo(4, 10, 0),
  },
  {
    id: crmCompanies[26].id,
    name: crmCompanies[26].name,
    domain: "nordicpartners.example.com",
    industry: "Financial Services",
    type: "Prospect",
    size: "51-200",
    location: "Stockholm, Sweden",
    ownerId: salesOwners[4].id,
    website: "https://nordicpartners.example.com",
    primaryContactId: "con-084",
    source: "Outbound",
    openDealCount: 0,
    openPipelineValue: 0,
    wonRevenue: 0,
    lastActivity: timestampAgo(7, 9, 0),
    tags: ["partnerships", "international"],
    description:
      "Nordic Partners Group is a Stockholm-based financial advisory firm. Erik responded to an outbound email but hasn't committed to a demo.",
    activityTimeline: [
      activity(
        "ca-q01",
        "email",
        timestampAgo(7, 9, 0),
        "Outbound follow-up",
        "Second follow-up email sent.",
        undefined,
      ),
      activity(
        "ca-q02",
        "email",
        timestampAgo(14, 9, 0),
        "Initial outreach",
        "Cold email with Nordic market case study.",
        undefined,
      ),
    ],
    tasks: [],
    deals: [],
    createdAt: daysAgo(7),
  },
  {
    id: crmCompanies[27].id,
    name: crmCompanies[27].name,
    domain: "lumieretech.example.com",
    industry: "Technology",
    type: "Customer",
    size: "51-200",
    location: "Paris, France",
    ownerId: salesOwners[6].id,
    website: "https://lumieretech.example.com",
    primaryContactId: "con-085",
    source: "Event",
    openDealCount: 1,
    openPipelineValue: 48000,
    wonRevenue: 72000,
    lastActivity: timestampAgo(2, 11, 0),
    tags: ["tech", "international"],
    description: "Lumiere Tech Paris builds AI-powered customer support tools. Camille met Isla at VivaTech Paris.",
    phone: "+33 1 55 55 0176",
    address: "88 Avenue des Champs-Élysées, Paris, France",
    activityTimeline: [
      activity(
        "ca-r01",
        "call",
        timestampAgo(2, 11, 0),
        "Upsell discussion",
        "Camille interested in API premium tier.",
        "Isla Grant",
      ),
      activity(
        "ca-r02",
        "meeting",
        timestampAgo(10, 14, 0),
        "VivaTech follow-up",
        "Met at VivaTech, discussed integration needs.",
        "Isla Grant",
      ),
    ],
    tasks: [
      task(
        "ct-r01",
        "Send API premium tier proposal",
        "pending",
        "high",
        daysFromNow(3),
        timestampAgo(2, 11, 0),
        "Isla Grant",
      ),
    ],
    notes: [
      note(
        "cn-r01",
        "Camille's team uses our API heavily. Premium tier would give them higher rate limits and priority support.",
        "Isla Grant",
        timestampAgo(2, 11, 30),
      ),
    ],
    deals: [
      deal("cd-r01", "API Premium Tier", 48000, "Negotiation", daysFromNow(10), timestampAgo(2, 11, 0)),
      deal("cd-r02", "Base Platform", 72000, "Closed Won", null, timestampAgo(260, 9, 0)),
    ],
    createdAt: daysAgo(260),
    updatedAt: timestampAgo(2, 11, 0),
  },
  {
    id: crmCompanies[28].id,
    name: crmCompanies[28].name,
    domain: "willowcreekhr.example.com",
    industry: "Professional Services",
    type: "Prospect",
    size: "11-50",
    location: "Portland, OR",
    ownerId: salesOwners[5].id,
    website: "https://willowcreekhr.example.com",
    primaryContactId: "con-086",
    source: "Inbound",
    openDealCount: 1,
    openPipelineValue: 22000,
    wonRevenue: 0,
    lastActivity: timestampAgo(6, 10, 0),
    tags: ["hr-tech", "consulting"],
    description: "Willow Creek HR is an HR consulting firm. Hannah submitted a demo request through our website.",
    phone: "+1 (503) 555-0132",
    address: "520 SW 6th Ave, Portland, OR 97204",
    activityTimeline: [
      activity(
        "ca-s01",
        "call",
        timestampAgo(6, 10, 0),
        "Demo call",
        "Hannah walked through their requirements.",
        "Lucas Moreau",
      ),
      activity(
        "ca-s02",
        "email",
        timestampAgo(10, 9, 0),
        "Demo request",
        "Submitted form asking for a demo.",
        undefined,
      ),
    ],
    tasks: [
      task(
        "ct-s01",
        "Send proposal after demo",
        "pending",
        "medium",
        daysFromNow(5),
        timestampAgo(6, 10, 0),
        "Lucas Moreau",
      ),
    ],
    notes: [
      note(
        "cn-s01",
        "Hannah needs CRM with strong email tracking. Her team lives in their inbox.",
        "Lucas Moreau",
        timestampAgo(6, 10, 30),
      ),
    ],
    deals: [
      deal("cd-s01", "Professional Tier Annual", 22000, "Qualification", daysFromNow(21), timestampAgo(6, 10, 0)),
    ],
    createdAt: daysAgo(250),
    updatedAt: timestampAgo(6, 10, 0),
  },
  {
    id: crmCompanies[29].id,
    name: crmCompanies[29].name,
    domain: "horizonutil.example.com",
    industry: "Logistics",
    type: "Customer",
    size: "501-1000",
    location: "Phoenix, AZ",
    ownerId: salesOwners[3].id,
    website: "https://horizonutil.example.com",
    primaryContactId: "con-087",
    source: "Outbound",
    openDealCount: 1,
    openPipelineValue: 95000,
    wonRevenue: 180000,
    lastActivity: timestampAgo(3, 10, 0),
    tags: ["utilities", "energy"],
    description:
      "Horizon Utilities provides energy and utility services across the Southwest US. Won through outbound prospecting in 2025.",
    phone: "+1 (602) 555-0198",
    address: "2390 E Camelback Rd, Phoenix, AZ 85016",
    activityTimeline: [
      activity(
        "ca-t01",
        "call",
        timestampAgo(3, 10, 0),
        "Expansion planning",
        "Ben wants to add field service management.",
        "Ethan Brooks",
      ),
      activity(
        "ca-t02",
        "email",
        timestampAgo(10, 9, 0),
        "Renewal reminder",
        "Sent renewal reminder for Q4.",
        undefined,
      ),
      activity(
        "ca-t03",
        "meeting",
        timestampAgo(20, 14, 0),
        "Q2 review",
        "Reviewed platform adoption across 4 regions.",
        "Ethan Brooks",
      ),
    ],
    tasks: [
      task(
        "ct-t01",
        "Build field service demo",
        "in_progress",
        "high",
        daysFromNow(4),
        timestampAgo(3, 10, 0),
        "Ethan Brooks",
      ),
      task(
        "ct-t02",
        "Send Q4 renewal proposal",
        "pending",
        "medium",
        daysFromNow(10),
        timestampAgo(3, 10, 0),
        "Ethan Brooks",
      ),
    ],
    notes: [
      note(
        "cn-t01",
        "Ben's team has adopted the platform well. They use it across 4 of their 6 regions. Good expansion opportunity.",
        "Ethan Brooks",
        timestampAgo(3, 10, 30),
      ),
    ],
    deals: [
      deal("cd-t01", "Field Service Module", 95000, "Proposal", daysFromNow(21), timestampAgo(3, 10, 0)),
      deal("cd-t02", "Base Platform", 180000, "Closed Won", null, timestampAgo(420, 9, 0)),
    ],
    createdAt: daysAgo(420),
    updatedAt: timestampAgo(3, 10, 0),
  },
];

export const typeOptions: readonly CompanyType[] = ["Prospect", "Customer", "Partner", "Former Customer"] as const;

export const industryOptions: readonly CompanyIndustry[] = [
  "Technology",
  "Healthcare",
  "Financial Services",
  "Retail",
  "Manufacturing",
  "Logistics",
  "Professional Services",
  "Education",
  "Real Estate",
  "Hospitality",
] as const;

export const sizeOptions: readonly CompanySize[] = ["1-10", "11-50", "51-200", "201-500", "501-1000", "1001+"] as const;

const companyCustomFieldValueSeed: Record<string, Company["customFields"]> = {
  c1: { business_model: "B2B SaaS", annual_revenue: 48000000, renewal_month: "March" },
  c2: { business_model: "Hardware", annual_revenue: 125000000, renewal_month: "July" },
  c3: { business_model: "B2B SaaS", renewal_month: "September" },
  c4: { business_model: "Professional Services", annual_revenue: 74000000 },
  c5: { business_model: "Marketplace", annual_revenue: 31000000, renewal_month: "January" },
  c6: { business_model: "Professional Services" },
  c7: { business_model: "E-commerce", annual_revenue: 9500000, renewal_month: "November" },
  c9: { business_model: "B2B SaaS", renewal_month: "June" },
};

for (const company of companies) {
  const seed = companyCustomFieldValueSeed[company.id];
  if (seed) {
    company.customFields = seed;
  }
}
