import { addDays, setHours, setMinutes } from "date-fns";

import { today } from "./period";
import { type CrmMeeting, meetingSchema } from "./schema";

function atTime(dayOffset: number, hour: number, minute = 0): Date {
  return setMinutes(setHours(addDays(today, dayOffset), hour), minute);
}

const meetingFixtures = [
  {
    id: "mtg-1",
    title: "Discovery call",
    companyId: "c1",
    contact: "Cameron Ruiz",
    ownerId: "arham",
    dayOffset: 1,
    hour: 9,
    minute: 30,
    durationMinutes: 45,
    type: "Discovery call",
  },
  {
    id: "mtg-2",
    title: "Product demo",
    companyId: "c2",
    contact: "Nina Petrova",
    ownerId: "ammar",
    dayOffset: 2,
    hour: 11,
    minute: 0,
    durationMinutes: 60,
    type: "Product demo",
  },
  {
    id: "mtg-3",
    title: "Proposal review",
    companyId: "c3",
    contact: "Tomas Lindqvist",
    ownerId: "sofia",
    dayOffset: 3,
    hour: 14,
    minute: 30,
    durationMinutes: 30,
    type: "Proposal review",
  },
  {
    id: "mtg-4",
    title: "Follow-up call",
    companyId: "c4",
    contact: "Ava Thompson",
    ownerId: "ethan",
    dayOffset: 4,
    hour: 10,
    minute: 0,
    durationMinutes: 30,
    type: "Follow-up",
  },
  {
    id: "mtg-5",
    title: "Pricing negotiation",
    companyId: "c5",
    contact: "Mateo Silva",
    ownerId: "nadia",
    dayOffset: 6,
    hour: 13,
    minute: 0,
    durationMinutes: 60,
    type: "Negotiation",
  },
  {
    id: "mtg-6",
    title: "Product demo",
    companyId: "c6",
    contact: "Priya Raman",
    ownerId: "arham",
    dayOffset: 8,
    hour: 9,
    minute: 0,
    durationMinutes: 45,
    type: "Product demo",
  },
  {
    id: "mtg-7",
    title: "Discovery call",
    companyId: "c7",
    contact: "Felix Bauer",
    ownerId: "lucas",
    dayOffset: 10,
    hour: 15,
    minute: 0,
    durationMinutes: 45,
    type: "Discovery call",
  },
  {
    id: "mtg-8",
    title: "Proposal review",
    companyId: "c8",
    contact: "Hana Sato",
    ownerId: "isla",
    dayOffset: 12,
    hour: 11,
    minute: 30,
    durationMinutes: 30,
    type: "Proposal review",
  },
  {
    id: "mtg-9",
    title: "Follow-up call",
    companyId: "c9",
    contact: "Omar Farouk",
    ownerId: "kenji",
    dayOffset: 15,
    hour: 16,
    minute: 0,
    durationMinutes: 30,
    type: "Follow-up",
  },
  {
    id: "mtg-10",
    title: "Discovery call",
    companyId: "c10",
    contact: "Lena Kowalski",
    ownerId: "ammar",
    dayOffset: 18,
    hour: 9,
    minute: 30,
    durationMinutes: 45,
    type: "Discovery call",
  },
  {
    id: "mtg-11",
    title: "Product demo",
    companyId: "c11",
    contact: "Rosa Delgado",
    ownerId: "sofia",
    dayOffset: 22,
    hour: 14,
    minute: 0,
    durationMinutes: 60,
    type: "Product demo",
  },
  {
    id: "mtg-12",
    title: "Pricing negotiation",
    companyId: "c12",
    contact: "Jonas Weber",
    ownerId: "arham",
    dayOffset: 26,
    hour: 10,
    minute: 30,
    durationMinutes: 60,
    type: "Negotiation",
  },
  {
    id: "mtg-13",
    title: "Proposal review",
    companyId: "c13",
    contact: "Claire Dubois",
    ownerId: "ethan",
    dayOffset: 30,
    hour: 11,
    minute: 0,
    durationMinutes: 30,
    type: "Proposal review",
  },
  {
    id: "mtg-14",
    title: "Discovery call",
    companyId: "c14",
    contact: "Samira Haddad",
    ownerId: "nadia",
    dayOffset: 45,
    hour: 13,
    minute: 30,
    durationMinutes: 45,
    type: "Discovery call",
  },
];

export const crmMeetings: CrmMeeting[] = meetingFixtures.map((meeting) =>
  meetingSchema.parse({
    ...meeting,
    startsAt: atTime(meeting.dayOffset, meeting.hour, meeting.minute),
  }),
);

export function upcomingMeetings(meetings: CrmMeeting[], until: Date, ownerId: string | null): CrmMeeting[] {
  return meetings
    .filter((meeting) => meeting.startsAt <= until && (ownerId === null || meeting.ownerId === ownerId))
    .sort((a, b) => a.startsAt.getTime() - b.startsAt.getTime());
}
